### ISSUE TITLE
The Response content must be a string or object implementing 

### ISSUE THREAD

**Issue by Nagraj722** [laravel/socialite#290]
I'm trying to get user details using google , facebook and Twitter. but im unable to success from last two days.  after login gmail auth, url redirected to callback url and getting below error.

The Response content must be a string or object implementing __toString(), "object" given.

  //Controller code
 public function redirectToProvider()
    {
        return Socialite::driver('google')->redirect();
    }

     public function googleCallback()
    {      
            try {
             return $user = Socialite::driver('google')->userFromToken('google');
            }
            catch (GuzzleHttp\Exception\ClientException $e) {
               dd($e->response);
            }

    }

//env
GOOGLE_CLIENT_ID=--------------------.googleusercontent.com
GOOGLE_CLIENT_SECRET=------
GOOGLE_URL=http://example/subscribe/google/callback

//services.php
 'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),         
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect' =>  env('GOOGLE_URL'),
    ],
//routes
Route::get('subscribe/google', 'Auth\LoginController@redirectToProvider');
Route::get('subscribe/google/callback', 'Auth\LoginController@googleCallback');

I have enabled google+ API also
Please help me

Thanking you in advance

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
