### ISSUE TITLE
Failed login with google

### ISSUE THREAD

**Issue by alexgomez88** [laravel/socialite#294]
I got this issue ones i upload to the server:

Client error: `POST https://accounts.google.com/o/oauth2/token` resulted in a `400 Bad Request` response: { "error": "invalid_request", "error_description": "Missing required parameter: code" }

any solution, thx in advance.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Hujjat** [comment]
I think this is bug, I tried all the options but it's not working. Please test it with latest version of Google API. 

It works just fine for Facebook. But for Google, the code is missing.

**Comment by Nirjhor3029** [comment]
same problem here i'm just facing it. 
the funny thing is i recently found a solution from stackoverflow that from 
------------------------------
the solution is to remove the profile from scopes in vendor\laravel\socialite\src\Two\GoogleProvider.php

protected $scopes = [
    'openid',
    'email',
];
-----------------
but when i removed the 'profile' scope it works fine for login only [ like who ever sign in/sign up previously for them that works fine ]
But for new user they can't login/sign up ... 
if anyone can find some solution kindly suggest .
[thanks in advance]

**Comment by rejauldu** [comment]
When I removed profile I don't see error but the name and nickname parameter becomes null.

**Comment by spangeni44** [comment]
Have anyone found solution to this problem?

**Comment by Hujjat** [comment]
@spangeni44 Yes we did. You should modify the socialite package source code. as @Nirjhor3029  said

**Comment by spangeni44** [comment]
@Hujjat @Nirjhor3029  solution does not give name of user thats not a solution.

**Comment by felix2056** [comment]
Same problem. Nobody found a solution?

**Comment by felix2056** [comment]
I found a fix for this.
Google sent a payload back after requesting OAUTH. The payload contains a code object that you are supposed to send as headers along with the callback route on Sociallite.

Sociallite is not sending the code respose back to google thus the error.
Fixed it without having to remove profile from the scopes `vendor\laravel\socialite\src\Two\GoogleProvider.php`

`Object { code: "4/vAEVuHyCL3tmV8lv6jbJvsxllVOz4tq-iNxY5AC2fMJqTZMgu8u_B5S98mQCjPu1mGjskL9AA836zoT2sp8huNQ", scope: "email+profile+openid+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email", authuser: "1", session_state: "ae674d53c3d40e64a9a8aa79089b955a4e552bfc..cd9f", prompt: "consent" }`

**Comment by Adron55** [comment]
@felix2056 How did you solve this problem ? Can u share your solution ? Thanks in advance

**Comment by InfiniteCoder96** [comment]
Hi guys,
 is there any solution to this without removing 'profile' from $scopes in GoogleProvider.php ?

**Comment by dilpreet91** [comment]
This issue if from date on 6 Nov 2018, but still no solution on this. @driesvints  I tried the shared discussion forums also. Could you please advise on as, that will be helpfull

Thanks in advance

**Comment by lynmije** [comment]
> I found a fix for this.
> Google sent back a payload after requesting OAUTH. The payload contains a code object that you are supposed to send as headers along with the callback route on Socialite.
> 
> Socialite is not sending the code response back to google thus the error.
> Fixed it without having to remove profile from the scopes `vendor\laravel\socialite\src\Two\GoogleProvider.php`
> 
> `Object { code: "4/vAEVuHyCL3tmV8lv6jbJvsxllVOz4tq-iNxY5AC2fMJqTZMgu8u_B5S98mQCjPu1mGjskL9AA836zoT2sp8huNQ", scope: "email+profile+openid+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email", authuser: "1", session_state: "ae674d53c3d40e64a9a8aa79089b955a4e552bfc..cd9f", prompt: "consent" }`

Can you share how you fixed the issue?

**Comment by MrCrap** [comment]
why has the case been closed?
what is the solution?

**Comment by estissy** [comment]
Any progress here?

**Comment by Eman152** [comment]
can anyone have reach to a solution?

**Comment by jonjieviduya** [comment]
Try to set the redirect URIs in your google account.

**Comment by jonjieviduya** [comment]
Try to set the redirect in your services inside the config folder, like so:

```
'google' => [
     'client_id' => env('GOOGLE_CLIENT_ID'),
     'client_secret' => env('GOOGLE_CLIENT_SECRET'),
     'redirect' => 'setYourURLHere'
]
```

**Comment by CosminAndrei2000** [comment]
> I found a fix for this.
> Google sent back a payload after requesting OAUTH. The payload contains a code object that you are supposed to send as headers along with the callback route on Socialite.
> 
> Socialite is not sending the code response back to google thus the error.
> Fixed it without having to remove profile from the scopes `vendor\laravel\socialite\src\Two\GoogleProvider.php`
> 
> `Object { code: "4/vAEVuHyCL3tmV8lv6jbJvsxllVOz4tq-iNxY5AC2fMJqTZMgu8u_B5S98mQCjPu1mGjskL9AA836zoT2sp8huNQ", scope: "email+profile+openid+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email", authuser: "1", session_state: "ae674d53c3d40e64a9a8aa79089b955a4e552bfc..cd9f", prompt: "consent" }`

Can you please share your solution? Thanks.

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
