### ISSUE TITLE
403 error in google auth

### ISSUE THREAD

**Issue by atanderG** [laravel/socialite#301]
i m using laravel 5.6 and socialite 3.0, all other APi are working except google showing HTTP Error 403 - Forbidden. I have tried everywhere on google, stackoverflow but no answar. What is the issue

**Comment by driesvints** [comment]
Can you post the links to the places where you asked for help? This would help us find out what the problem is faster.

**Comment by atanderG** [comment]
The link is : https://www.openbooktutorials.com/home

I have to remove profile, and id from socialte googleManager.php class to
make it working.. (Now it is working).
Have I done the right thing? or there is some thing else I might be missing?

Thanks

**Comment by driesvints** [comment]
This isn't a link to stackoverflow like you said. Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by atanderG** [comment]
https://stackoverflow.com/questions/53348777/socialite-laravel-authantication-error-with-google-api/53349266#53349266

**Comment by benjam-es** [comment]
Hi,

This is an issue that is happening for me too. I have tried all solutions from several links on stackoverflow and laracasts found via a google search.

For me, I have a test website and live website... https://test.mysite.com and https://www.mysite.com. The odd thing is that this was fully tested and working (and still does) on the test domain, but give me a 403 error when using google on the live domain. Other providers (Facebook/Twitter/Linkedin) all work properly still on both test and live.

From the suggestions relating to 'scope', if I manually edit the callback URL to edit the scopes and press enter, the login process completes. (see below)

> https://www.mysite.com/login/google/callback?code=HIDDEN-CODE&scope=openid%20email%20profile%20https://www.googleapis.com/auth/plus.me%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=2&hd=HIDDENUSER&session_state=SESSION&prompt=consent


remove the scopes that are NOT within `GoogleProvider.php $scopes`


> https://www.mysite.com/login/googlecallback?code=HIDDEN-CODE&scope=openid%20email%20profile&authuser=2&hd=HIDDENUSER&session_state=SESSION&prompt=consent

**Comment by driesvints** [comment]
@benjam-es can you try upgrading to the latest laravel and socialite version?

**Comment by benjam-es** [comment]
The project is currently heavily tied to Laravel 5.5.x meaning im stuck on Socialite v3.x at the moment.

**Comment by driesvints** [comment]
@benjam-es does using the solution from here work? https://github.com/laravel/socialite/pull/319#issuecomment-450829869

**Comment by benjam-es** [comment]
From bugsnag also if this helps


  | public function user()
-- | --
  | {
  | if ($this->hasInvalidState()) {
  | throw new InvalidStateException;
 }
  
$response = $this->getAccessTokenResponse($this->getCode());

**Comment by benjam-es** [comment]
> @benjam-es does using the solution from here work? [#319 (comment)](https://github.com/laravel/socialite/pull/319#issuecomment-450829869)

I've not pulled in that dev branch, and am still getting the same problem.

**Comment by atanderG** [comment]
https://www.openbooktutorials.com/

**Comment by benjam-es** [comment]
Not sure what that URL is for.. perhaps to do with my previous typo of NOT instead of NOW?

It's just a homepage of tutorials unrelated to this issue.

**Comment by driesvints** [comment]
@benjam-es unfortunately we don't support 3.0 anymore. You'll have to upgrade and see if the newer version helps.
