### ISSUE TITLE
Type error: Argument 1 passed to league\OAuth1\Client\Server::getTokenCredentials() in twitter 

### ISSUE THREAD

**Issue by vinothabc** [laravel/socialite#308]
Type error: Argument 1 passed to league\OAuth1\Client\Server::getTokenCredentials(). 
When i am first time twitter login, get this issue. 
Refer this screen short
                  https://prnt.sc/lu2jpi

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
