### ISSUE TITLE
Issue with Google+ Provider

### ISSUE THREAD

**Issue by bocahptualang** [laravel/socialite#314]
Error when authenticate with google+ provider (Socialite version 4.0.0). 
I tried downgrade socialite version to 3.1.1 and it is working. 

![image](https://user-images.githubusercontent.com/9653331/50205537-2bbafe00-039b-11e9-8829-224155f0adfa.png)

`GoogleProvider.php`
![image](https://user-images.githubusercontent.com/9653331/50205464-e5fe3580-039a-11e9-8a66-cb3272749cad.png)

Anyway, is there any way to override mapping function from response we get from provider to user object? it would be nice if got one.

**Comment by rjvandoesburg** [comment]
I too am experiencing this problem with a newly created token. On another website (different token) I am still receiving `displayName`.

Attached 2 different responses:
[old.txt](https://github.com/laravel/socialite/files/2694966/old.txt)
The old one is from another implementation

[new.txt](https://github.com/laravel/socialite/files/2694965/new.txt)
This is the response I'm getting from a newly generated key.

As they differ so much I think I'm doing something different so I'll keep looking into it.

Cheers,

**Comment by NicolaeCasir** [comment]
Good job man. I just wanted to make PR... With email its OK.. but with name, its a problem... i've edited GoogleProvider in vendor but im waiting for merge!

**Comment by rjvandoesburg** [comment]
Merging the PR will break my other implementations so more investigation is needed or the PR need to be updated to accommodate both responses

**Comment by driesvints** [comment]
Just merged the PR. I'll tag a new release in a bit.
