### ISSUE TITLE
Bad Request - Invalid Scope - Scope Parameter Error - AADSTS70011

### ISSUE THREAD

**Issue by murugesan-clarion** [laravel/socialite#315]
> Client error: `POST https://login.microsoftonline.com/common/oauth2/v2.0/token` resulted in a `400 Bad Request` response: {"error":"invalid_scope","error_description":"AADSTS70011: The provided request must include a 'scope' input parameter.\ (truncated...)

We have created an App under MS app section & using it for Calendar synchronization. While we are trying to authenticate the MS account from our website, it returns back to the website & throwing the above error.

Code: Socialite::driver($provider)->stateless()->user(); 

Specifically, when we used the above statement, we are getting the error. We tried changing all the App permission, tried with new App ID/Key etc., But again getting the same error. Not sure what we are missing. By the way, the library codes which we are using is 3 months old (Version 3.3). Not sure it's because of this as it was working perfectly fine 3 months ago.

Your timely help would enable us to go live with this feature soon.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
