### ISSUE TITLE
Facebook - loging via telephone number

### ISSUE THREAD

**Issue by lipiniak** [laravel/socialite#320]
Hi, 
Im using socialite for some time and i faced problem with loging via facebook. 
Some users got new Facebook acounts registered via telephone number not email, so they are loging via phone number and e-mail field is empty. On my application socialite module is throwing errors that it cant find email adress or email is empty. 
Is there any override or solution for this problem?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by driesvints** [comment]
Our user implementation only allows for email addresses as authentication so I don't think this is a bug. Maybe the Facebook provider from here does what you need? https://socialiteproviders.netlify.com/providers/facebook.html
