### ISSUE TITLE
Dynamic configuration is giving error for Google.

### ISSUE THREAD

**Issue by gaursinghveer007** [laravel/socialite#330]
I am trying to set dynamic configuration for Google Login. Please check below code. I am using Php framework.

$config = [
                'client_id'    => 'xxxxxxxxxxxxxxxxxxx',
                'client_secret' => 'xxxxxxxxxxxxxxxxxx',
                'redirect'     => 'http://www.test.com/google/callback/',
];

return Socialite::buildProvider(\Laravel\Socialite\Two\GoogleProvider::class, $config);

When running this code it's showing "The Response content must be a string or object implementing __toString(), "object" given.".

Please help me out

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
