### ISSUE TITLE
confirm twice redirect outside handleCallback

### ISSUE THREAD

**Issue by EntonoX** [laravel/socialite#331]
Hello,

I came accross an issue which i found quite strange. i have this callback function:

public function handleProviderCallback(Request $request, $provider)
    {
        try {
            $socialUser = Socialite::with($provider)->user();
            if ($socialUser) {
                $this->socialLogin($request, $socialUser, $provider, $socialUser->token);
            }
        } catch (InvalidStateException $exception) {
            return redirect()->back()->with('error', __('auth::auth.noProviderAuthentication'));
        }
        return redirect()->back()->with('error', __('auth::auth.noSocialLoginPossible'));
    }

The socialLogin function contains some other code but at the end of the function calls 
`return redirect($this->redirectTo);`

Now with microsoft as provider i get the Microsoft Oauth2 confirmation screen, click approve but then i need to click approve again. I also see in networking that a route 'reprocess?ctx=...' is called.

When i move the redirect inside the 'handleProviderCallback' all work as expected and i have to click only once in the Microsoft Oauth2 screen.

Is this expected behaviour?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
