### ISSUE TITLE
Enhancement: interface with Instagram

### ISSUE THREAD

**Issue by AlessBet** [laravel/socialite#333]
Hi all, 
would it be possible to expand the library to be able to interface with Instagram so that social login using it will be possible?

I would like to contribute more but my coding skills are way too limited.

**Comment by driesvints** [comment]
Heya, you can use this one: https://socialiteproviders.netlify.com/providers/instagram.html

**Comment by selvakumar143** [comment]
Hi when i trying to login Instagram its throw error "Oops, an error occurred."

**Comment by driesvints** [comment]
@selvakumar143 you'll have to post this to their issue tracker.

**Comment by kossa** [comment]
@driesvints any solution ?

**Comment by monika-mni** [comment]
I am facing the same issue with Instagram login. Can anyone please help here!

![https-www-instagram-com-oauth-authorize-client_id-349148989642877-redirect_uri-https-staging-sa-aec-clients-co-in-socialloginplus-callback-instagram-scope-basic-response_type-code-state-LyMzUfRXLmvmMJZv4gE4G7xmZ](https://user-images.githubusercontent.com/67259118/97416308-457ce300-192c-11eb-81f9-6abcf1a475f9.png)

**Comment by Me1ales** [comment]
you need add account to instagram testers, to see full error
