### ISSUE TITLE
Facebook OAuth exception - the app is configured as a desktop app

### ISSUE THREAD

**Issue by nagavinodcse** [laravel/socialite#334]
```Client error: `POST https://graph.facebook.com/v3.0/oauth/access_token` resulted in a `400 Bad Request` response: {"error":{"message":"The request is invalid because the app is configured as a desktop app","type":"OAuthException","cod (truncated...)```

i am getting this error when i am trying to login using facebook any ideas about this ? please do give any suggestions to get this work out.......

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
