### ISSUE TITLE
Make sure Google Provider is compatible with Google Sign-in

### ISSUE THREAD

**Issue by driesvints** [laravel/socialite#337]
Since the old Google Plus functionality is going to be deprecated we'll need to make sure that we can use the suggested alternative Google Sign-in instead.

New OAuth2 functionality: https://developers.google.com/identity/protocols/OAuth2
Shutdown notice: https://developers.google.com/+/api-shutdown

**Comment by No148** [comment]
@driesvints I tried to migrate to google sign-in using version 3 of socialite. I read the documentation and found this notes [https://developers.google.com/identity/sign-in/web/quick-migration-guide](url)
I have a custom socialtite provider so I was able to override methods from standart providers of socialite.
I created new api keys google sign-in, disabled google+ api in console and it worked as usually.

**Comment by No148** [comment]
@eaverdeja I don't really know for sure at the moment... I've changed api key and created a specific api key for google sign-in. (which was only possible from this page https://developers.google.com/identity/sign-in/web/sign-in) After using it I just have my fingers crossed... But everything seems to be working fine right now. I wish I knew more, mate!

**Comment by rajjanorkar** [comment]
- Just pull 3.0.x-dev
- No need to change anything in google developer console
- No need to change/create new api key/secrete etc.
- No other changes if you are not adding any additional scope (other than what package have)

It should just work fine.. i Tested it and it worked.

**Comment by cincauhangus** [comment]
how can i make this compatible with laravel 5.2.x?

**Comment by driesvints** [comment]
@cincauhangus 5.2.x isn't supported anymore. Please upgrade to the latest version.

**Comment by Casperhr** [comment]
Any plans for a 2.x fix?

**Comment by driesvints** [comment]
@Casperhr we actually pushed a 2.0 fix a couple of days ago. Use `2.0.x-dev` to pull it in.

**Comment by driesvints** [comment]
Friendly reminder to not rely on `-dev` versions to long and to upgrade your apps eventually.
