### ISSUE TITLE
Cannot login with state, if I use multi guard

### ISSUE THREAD

**Issue by 2bj** [laravel/socialite#338]
If I logged in one of my guards (for example, `guard:admin`), I cannot login with another guard (for example `guard:web`) with socialite with state (without state works fine), because session always regenerated for every refresh.

Is it bug or feature? :)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
