### ISSUE TITLE
Logging in with bitbucket isn't working as expected

### ISSUE THREAD

**Issue by wotta** [laravel/socialite#339]
So I am running against a problem which I didn't expect when I follow the documentation.

I have the following version of socialite installed (composer.lock):
```
"name": "laravel/socialite",
"version": "v4.0.3",
```

And I am running the following code:
```php
try {
    /** @var AbstractUser $socialiteUser */
    $socialiteUser = Socialite::driver($provider)->user();
} catch (Throwable $exception) {
    return redirect()->back()->withMessage(
        $exception->getResponse()->getBody()->getContents()
    );
}
```

This will always get an exception back.
So I tracked this down to the point where socialite is always asking for a "code" that should be in the request but is always `null`.

I hope anyone has an idea on why this is going wrong.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by wotta** [comment]
@driesvints Thanks for the reply, I have posted my question with link on `Laracasts` but I strongly have the feeling that the functionality on itself isn't actually working.

That's also a small problem with this package since testing this can be very hard.
When Laracasts can't help would there be an option to chat somewhere so to figure this one out?

**Comment by driesvints** [comment]
At the moment I don't have the time to look into this further so appreciating any help with this.

**Comment by driesvints** [comment]
Just tested this with the latest Socialite release and it works as expected.

I believe the `back` part of your code is causing you to get redirected back to bitbucket oauth screen which then fails because the code isn't sent along. This is normal and you shouldn't use `back`. Instead in your `catch` you should direct to whatever screen you came from.
