### ISSUE TITLE
Sending login token back to frontend after login

### ISSUE THREAD

**Issue by maidul98** [laravel/socialite#341]
My auth is done using a Passport. I have successfully logged in and return the callback with the user. However, when the frontend hits the endpoint that sends them off to Google Login, there is no way to return a  token from the first endpoint since the user already left the site. How can I send back a token to frontend? Or should I use something else to login users via social accounts on the frontend side (ex: https://www.npmjs.com/package/satellizer)?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
