### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by tecreasey** [laravel/socialite#344]
Is it possible to create a way to use Magento with Laravel Socialite?

**Comment by driesvints** [comment]
Not as a 1st party. I checked https://socialiteproviders.netlify.com/about.html but there wasn't one listed so you'll have to build your own or search for one.

**Comment by tecreasey** [comment]
I am happy having a go at creating one I was just wondering whether it could be done.

**Comment by driesvints** [comment]
Socialite can have custom providers (as you see with the link above) but I don't know anything about Magento to know how that would be implemented.
