### ISSUE TITLE
Logging in to a Linkedin profile that doesn't have an email attached causes undefined offset 0

### ISSUE THREAD

**Issue by HoughtonChristopher** [laravel/socialite#347]
ln 98 in LinkedinProvider return json_decode($response->getBody(), true)['elements'][0]['handle~'];

**Comment by driesvints** [comment]
Okay, I can see this going wrong but how is it possible that a profile doesn't has an email attached?

**Comment by HoughtonChristopher** [comment]
I have absolutely no idea but I just experienced it.

Maybe not verifying it or signing up with a phone number? I'm not entirely sure.
