### ISSUE TITLE
Reconsider a new V3 release – Google Sign-in

### ISSUE THREAD

**Issue by meijdenmedia** [laravel/socialite#348]
Please reconsider the choice of making a stable tag for Laravel LTS 5.5 users.

------------

@driesvints 
I know we can use it like that but what i requested it to tag a release as it is stable and official working as per Google SignIn. as because all the LTS 5.5 users are affected I wanted you to tag that as soon as possible

_Originally posted by @msonowal in https://github.com/laravel/socialite/issues/335#issuecomment-460526059_

**Comment by driesvints** [comment]
We've decided to make a one-time exception since there's so many people asking for this.

Just released Socialite  v2.0.22 and v3.3.0 which should include the new updated Google driver and any changes from those branches.

These will be the very last released for Socialite v2 & v3.
