### ISSUE TITLE
Facebook is removing access to "certain permissions or features on Mar 28, 2019"

### ISSUE THREAD

**Issue by lphilps** [laravel/socialite#349]
We are getting notifications from Facebook that say:

> Access to the permissions and features listed below will expire on Mar 28, 2019.
>     user_gender
>     user_friends
>     user_age_range
>     user_link
> 
> If you still require access to these permissions and features, please submit for App Review to avoid losing access.

Socialite's FacebookProvider is, by default, requesting the following fields:

`['name', 'email', 'gender', 'verified', 'link'];`

Since gender and link appear in that list, I _think_ that Socialite calls through apps that don't have the special permissions will start to fail on March 28th?

I'll confess I'm not sure, but thought I would raise the issue so there would be some time to deal with it before the 28th if it's an issue.

**Comment by driesvints** [comment]
Thanks for reporting. I'll make sure to look into this before the above date.

**Comment by driesvints** [comment]
Heya. I've reviewed this but it just seems that you'll have to submit your app to App Review again to maintain this. So I don't think it's up to us to fix this.

I do however, wonder why Socialite needs these fields to authenticate. I feel like a lot of providers just try to retrieve too much information.

**Comment by lphilps** [comment]
Well, that's sort of the point I was trying to make.  The Facebook provider doesn't even use the gender value it fetches, so why bother to ask for it.  I was thinking a default set of fields of:
```
['name', 'email', 'first_name', 'last_name']
```
would make more sense?  These fields are all available to every app.  If you need gender or link, you'll have to justify that need to Facebook, then you can override the default set of fields with something like:
```
$socialiteDriver = Socialite::driver('facebook');
$socialiteDriver->fields(['name', 'email', 'first_name', 'last_name', 'gender', 'link']);
$user = $socialiteDriver->user();
```
Have a feeling if you don't change the default, then every user that doesn't have a privileged Facebook app, likely most of them, will have to add code like that above to override the defaults for the provider.

**Comment by driesvints** [comment]
We might want to remove it in a future version but for now let's keep it for the current release to not break people's apps. The date you specified above also seems to be only specific for yourself as I can't find an announcement anywhere with this date.

**Comment by migcosta** [comment]
@driesvints the "permission" dates are specific to every app. The older the app the sooner it will expire. In our case it will on 6 of april ( https://screencast.com/t/9I1dTgEE )

By requesting the gender and the link fields, without the proper permissions, those fields won't be sent back to the call back url. And that will also brake the people's apps, won't it @driesvints?

I agree with @lphilps. The default fields should be the ones that are available by default to every app.

**Comment by driesvints** [comment]
@migcosta I'm not saying you're wrong, I'm just saying we can't remove those fields on a point release. For apps that do require them they will break when the fields suddenly aren't sent back. At the moment the status is that Socialite requires these fields. We can remove them on the next major release. In that case, send in a PR to the master branch.
