### ISSUE TITLE
No support for Laravel 5.5 and 5.6

### ISSUE THREAD

**Issue by alxy** [laravel/socialite#351]
For some reason, socialite has no version that works with Laravel 5.5 or 5.6. Especially 5.5 is really bad, as it is a long term release.

Socialite 3.*:
```
"require": {
        "php": ">=5.6.4",
        "guzzlehttp/guzzle": "~6.0",
        "illuminate/contracts": "~5.4",
        "illuminate/http": "~5.4",
        "illuminate/support": "~5.4",
        "league/oauth1-client": "~1.0"
    },
```

Socialite 4.*:
```
"require": {
        "php": "^7.1.3",
        "ext-json": "*",
        "guzzlehttp/guzzle": "~6.0",
        "illuminate/contracts": "~5.7.0|~5.8.0",
        "illuminate/http": "~5.7.0|~5.8.0",
        "illuminate/support": "~5.7.0|~5.8.0",
        "league/oauth1-client": "~1.0"
    },
```
Is this on purpose?

**Comment by driesvints** [comment]
Yes, we only support the latest Laravel release for the libraries. LTS only applies to the framework. Please upgrade.

**Comment by daftspunk** [comment]
Just fork the library @alxy these are likely superficial differences anyway

**Comment by trandangkhoa489** [comment]
laravel 5.5: **composer require laravel/socialite "^3.2.0"**
Thằng khứa nào dùng laravel 5.5 hay 5.6 gì mà lỗi như trên thì cài version 3.2.0
