### ISSUE TITLE
Auth code via FB Mobile SDK resulting Invalid Verification Code

### ISSUE THREAD

**Issue by tonz341** [laravel/socialite#352]
I wonder if i can still use Socialite to authenticate FB code that came from Mobile SDK?
Web SDK works fine just code from Mobile SDK throwing Invalid Verification code.

We are trying to implement Login as FB in Flutter but after via facebook login it will generate code like this

EAANXyXf1v7cBAEgxk9Ox1lsfpoSBxZAgBNfl1GWVbyEZBCJQawOBMCmS4Vz5......

and trying to authenticate via Socialite will throw 

{
    "status": "error",
    "exception": "GuzzleHttp\\Exception\\ClientException",
    "code": "SystemError",
    "msg": "Client error: `POST https://graph.facebook.com/v2.10/oauth/access_token` resulted in a `400 Bad Request` response:\n{\"error\":{\"message\":\"Invalid verification code format.\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"H9CluATh6Az\"}}\n",
    "file": "/home/forge/api.thaimatch.com/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php",
    "line": 113
}

I check WEB format FB code and its different from MOBILE SDK code.

Question is can i still use socialite to reauthenticate fb code from SDK?

**Comment by ankurk91** [comment]
```php
try {
            $providerUser = Socialite::driver($provider)->userFromToken($accessToken);
        } catch (\Throwable $exception) {
            // Send actual error message in development
            if (config('app.debug')) {
                throw $exception;
            }

            return null;
        }
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by tonz341** [comment]
hi all sorry for the inconvenience i think this question must be invalid.
Authorized code can only be fetched via facebook sdk on web not on fb android sdk

fb android sdk can only generate user token

so this errors is popping out when we try to authenticate the user tokens from fb which throws this error.

thanks
