### ISSUE TITLE
Breaking changes has released as bug fix version in 2.0.21 & 2.0.22

### ISSUE THREAD

**Issue by isreehari** [laravel/socialite#356]
- Socialite Version: 2.0.21
- Socialite Version: 2.0.22

### Description:
There is breaking change in GoogleProvider between laravel/socialite:2.0.21 and laravel/socialite:2.0.22 but it released as minor fix

### Steps To Reproduce:

https://github.com/laravel/socialite/compare/v2.0.21...laravel:v2.0.22

https://github.com/laravel/socialite/releases/tag/v2.0.22
```
/**
     * {@inheritdoc}
     */
    protected function mapUserToObject(array $user)
    {
        $avatarUrl = Arr::get($user, 'picture');

        return (new User)->setRaw($user)->map([
            'id' => Arr::get($user, 'id'),
            'nickname' => Arr::get($user, 'nickname'),
            'name' => Arr::get($user, 'name'),
            'email' => Arr::get($user, 'email'),
            'avatar' => $avatarUrl,
            'avatar_original' => preg_replace('/\?sz=([0-9]+)/', '', $avatarUrl),
        ]);
    }

```

https://github.com/laravel/socialite/releases/tag/v2.0.21
```
 /**
     * {@inheritdoc}
     */
    protected function mapUserToObject(array $user)
    {
        return (new User)->setRaw($user)->map([
            'id' => $user['id'], 
            'nickname' => Arr::get($user, 'nickname'), 
            'name' => $user['displayName'],
            'email' => $user['emails'][0]['value'], 
            'avatar' => Arr::get($user, 'image')['url'],
            'avatar_original' => preg_replace('/\?sz=([0-9]+)/', '', Arr::get($user, 'image')['url']),
        ]);
    }
```

Which is causing other open source product: 

https://github.com/dreamfactorysoftware/df-oauth/pull/5#issue-266094088

Thanks,
Sreehari Inukollu

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
