### ISSUE TITLE
Regarding facebook login issue

### ISSUE THREAD

**Issue by HCIPL-HCIPL** [laravel/socialite#358]
- Socialite Version: 3.1
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: PDO

### Description:

Hello, 

I am using socialite 3.1 version using laravel 5.5 where I am successfully logged-in with Facebook into my system but after then it's taking too much time to get back to the system like 25 to 30 second. 

What can be fixed for the same? Please let me know. 

Thanks,

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
