### ISSUE TITLE
Integrate with Reactjs

### ISSUE THREAD

**Issue by jjvillegas17** [laravel/socialite#359]
How can I make a rest api with the redirectToProvider function because when I call it in my React app, it says cross origin error. Thanks!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by mitul69** [comment]
Hello, 

Is there any place where i can find the issue resolved
