### ISSUE TITLE
No Message error using g+ login

### ISSUE THREAD

**Issue by akilpatel** [laravel/socialite#361]
When i try logging in using G+ it works perfectly on localhost:: but doesnt work on live testing, it gives the error "no message" at "/vendor/laravel/socialite/src/Two/AbstractProvider.php".
![Screenshot 2019-04-29 at 4 13 33 PM](https://user-images.githubusercontent.com/49442775/56891342-c3430280-6a99-11e9-852b-52c4c3c08a4c.png)

```
 'google' => [
             'client_id' => '**********.apps.googleusercontent.com',
             'client_secret' => '*****',
            'redirect' => 'http://uat1gdg.***.com/login/google/callback',
        ],

```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
