### ISSUE TITLE
Change default scope delimiter to space

### ISSUE THREAD

**Issue by driesvints** [laravel/socialite#363]
I believe a space is the more sensible default as I've not seen too many examples using comma's.

See discussion here as well: https://github.com/laravel/passport/issues/1008

**Comment by johnson-jnr** [comment]
Hi @driesvints, is this issue still on? I'll really love to contribute. 
Thanks!

**Comment by driesvints** [comment]
@johnson-jnr yes :)

**Comment by Jimbolino** [comment]
i would advise against this.
comma seems to be more frequent than space:
(excuse my bad shell scripting skills)
```
jim@jim:~/socialiteproviders/providers/src$ ack scopeSeparator | grep "' '" | wc -l
32
jim@jim:~/socialiteproviders/providers/src$ ack scopeSeparator | grep "','" | wc -l
2
jim@jim:~/socialiteproviders/providers/src$ ack scopeSeparator | grep "';'" | wc -l
1
jim@jim:~/socialiteproviders/providers/src$ ack scopeSeparator | grep "'+'" | wc -l
3
jim@jim:~/socialiteproviders/providers/src$ ls -al | wc -l
165

165-32-2-1-3 = 127
```
source: https://github.com/SocialiteProviders/Providers/tree/master/src

**Comment by driesvints** [comment]
I'm gonna close this because this isn't much of an issue really. Might not be worth the breaking change.
