### ISSUE TITLE
Facebook no longer supports pre v3.2 apps by default

### ISSUE THREAD

**Issue by rennokki** [laravel/socialite#364]
Creating new Facebook apps are prior to v3.2 and v3.3 (for now). The latest version in Socialite is v3.0

**Comment by driesvints** [comment]
Does changing the version [here](https://github.com/laravel/socialite/blob/690c46cb572fb2f8a1a5520ff4b2446406ce5afd/src/Two/FacebookProvider.php#L22) fix it?

**Comment by rennokki** [comment]
Forgot to mention the problem itself: after a while, it throws ERR_TOO_MANY_REDIRECTS in the browser. It does't even hit Facebook itself on the way, it should have hit the redirect and display Facebook's OAuth consent page.

**Comment by driesvints** [comment]
I'm not sure what to do here tbh. Appreciating any help with this.

**Comment by driesvints** [comment]
@rennokki can you also please fill out the issue template?

**Comment by rennokki** [comment]
I'm late, as always. Idk, but a solution might be setting up the version on demand right within Socialite.

- Socialite Version: 4.1.3
- Laravel Version: 5.8.x
- PHP Version: 7.2
- Database Driver & Version: Facebook

### Description:
At the moment, Facebook no longer allows selecting v3.0 for fresh-new created apps in their Developers portal. The current Socialite Facebook supported Graph version is v3.0. The minimum allowed version is v3.2. This might be the problem that lead to ERR_TOO_MANY_REDIRECTS when following the redirect from the `->redirect()` method. While on ERR_TOO_MANY_REDIRECTS error page, the URL contains `v3.0`.

### Steps To Reproduce:
1. Install Socialite and create a new Facebook app within Developers portal. Set the Facebook app version to the lowest possible (v3.2 for now; < v3.2 cannot be selected).
2. Enable Facebook Login and add OAuth Valid Redirects and fill in the app settings.
3. Add the following code (try both with/without `->stateless()`):
```php
return Socialite::driver('facebook')->stateless()->redirect();
```
4. Watch the browser freeze for ~ 5 secs and then throwing ERR_TOO_MANY_REDIRECTS (on Chrome)

**Comment by mrpiagg** [comment]
Temporary fix is to change provider number to 3.3 in FacebookProvider
.. protected $version = 'v3.3';


And change function getCodeFields in AbstractProvider to (FB is not accepting response_type):

protected function getCodeFields($state = null)
    {
        if (strpos($this->redirectUrl, 'facebook') !== false) {
            $fields = [
                'client_id' => $this->clientId,
                'redirect_uri' => $this->redirectUrl,
                'scope' => $this->formatScopes($this->getScopes(), $this->scopeSeparator)
            ];
        } else {
            $fields = [
                'client_id' => $this->clientId,
                'redirect_uri' => $this->redirectUrl,
                'scope' => $this->formatScopes($this->getScopes(), $this->scopeSeparator),
                'response_type' => 'code',
            ];
        }

        if ($this->usesState()) {
            $fields['state'] = $state;
        }

        return array_merge($fields, $this->parameters);
    }

**Comment by driesvints** [comment]
@mrpiagg sounds like a good PR to fix this? 

@rennokki does the solution from @mrpiagg solve your problem?

**Comment by nosun** [comment]
My laravel version is 5.2, The Graph API version is 2.8, I got the same error.

After facebook auth the request, can not redirect to source site, display the error like

```
Sorry, something went wrong
Please try closing and re-opening your browser window.
```

**Comment by brandonburkett** [comment]
Is it possible to let the package users specific the facebook graph api version number? I see it is hard coded to v3.0, yet my newly created facebook login app is 3.3 (and unable to move it down to 3.0).

Any update on this topic?

**Comment by driesvints** [comment]
@brandonburkett it was mentioned above by @rennokki that this doesn't work: https://github.com/laravel/socialite/issues/364#issuecomment-490861661

Sadly I haven't found time to look into this yet and I also don't have a facebook account so appreciating a PR if anyone is up for it.

**Comment by brandonburkett** [comment]
@driesvints Got it.  For what it is worth, I did the following yesterday and everything worked on my end... BUT I am only using the turn-key Facebook login with no additional requested data.
- created a new FB login app at version 3.3
- used socialite (fb API version 3)
- and FB login worked fine (I did not hit any of the redirect issues)

I know this use case does not cover everything, but FB login (email, name permissions) worked with a new FB app at v3.3.

**Comment by suchal** [comment]
@brandonburkett  can you please explain "created a new fb login app at version 3.3" what do you mean by this? I can fix it and send a PR if I understand what you mean. And the community would really appreciate it if you could create a PR yourself.

**Comment by brandonburkett** [comment]
@suchal Hi!  Happy to explain.  In short, I was at 2.X and received an end of life notification from facebook on our API version, so I looked into upgraded to 3.3.  To do this:

- I created a new facebook app with API version 3.3 (login only with no additional requested data)
- Tested the login app by updating our facebook client id and secret in staging
- Socialite worked fine, even though the FB API version was pinned at 3.0 (hard coded I believe in socialite)

My use case was very simple though, just the turn-key with facebook (no app approval for additional data).  In short, I did not fully test everything that could have been impacted, just calling out login with facebook worked.

I hope that adds more clarity.

**Comment by rennokki** [comment]
I guess that my current case I was really isolated and under unknown circumstances. I guess there was some misconfiguration.

**Comment by brandonburkett** [comment]
@rennokki I still think it is an issue that the API version is pinned / hard coded in the project.  It should probably be bumped to 3.3.

**Comment by willwinberg** [comment]
I'm so confused. How do you even get the option to use the v3.3 api. When I make an app in the facebook developer portal, only v5 is available.

**Comment by kirkbushell** [comment]
This needs to be updated/changed immediately -  the old API versions are no longer supported after today.

**Comment by driesvints** [comment]
@kirkbushell still seems to be available until July 26, 2020: https://developers.facebook.com/docs/graph-api/changelog/

Everyone's free to send in prs. Please see https://github.com/laravel/socialite/issues/405

**Comment by kirkbushell** [comment]
@driesvints interesting... seems the emails FB are sending are telling a different story =\
