### ISSUE TITLE
Socialite v3.3 not using Linkedin V3 api url

### ISSUE THREAD

**Issue by Kofacts** [laravel/socialite#370]
- Socialite Version: 3.3
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version:

### Description:

Version 3.3 doesn't support the most recent Linkedin api web service. It still uses the v1 which throws the "Not enough permissions error"

### Steps To Reproduce:
Checkout V3.3 and below..

**Comment by olivernybroe** [comment]
LinkedIn does not have a version 3 api.
The reason for socialite not supporting linkedIn API v2 before socialite v4 is because changing that is a major change and most of the users need to adapt their code to LinkedIn V2 api.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
