### ISSUE TITLE
Add WHMCS Provider

### ISSUE THREAD

**Issue by strausmann** [laravel/socialite#372]
Please add the WHMCS OpenID Server as new Provider for Sociallite.

https://docs.whmcs.com/OpenID_Connect_Developer_Guide

**Comment by qWici** [comment]
@strausmann I believe that authorization using this provider is very narrowly specialized and will be rarely used

**Comment by driesvints** [comment]
Please see the readme. We're not accepting any more drivers. Try the socialiteproviders repo.
