### ISSUE TITLE
How can I get value of my own optional parameters from Github Socialite by using `with()` method?

### ISSUE THREAD

**Issue by satyakresna** [laravel/socialite#373]
Hi there, I just try to implement **optional parameters** feature based on Laravel Socialite using Github Provider. Is it supported in Socialite? According to the https://laravel.com/docs/5.8/socialite#optional-parameters documentation tell that
``
A number of OAuth providers support optional parameters in the redirect request. To include any optional parameters in the request, call the `with` method with an associative array.
``
So, I'm curious is it possible I can do that on Github?

My idea is the user can register meetup event by login with Github follow these steps:

1. Click **Login with Github** link
2. The system will redirect the user to Github login page. User fills username and password.
3. Github will send callback based on what I set in Socialite.
4. If I use **optional parameters** with `with()` method then I can get the optional parameters in `handleProviderCallback()` with `Illuminate\Http\Request`. But, the result is not expected.

This is my snippet code:

**Route in web.php**
``
Route::get('register/{provider}', 'ReservationController@doReservation');
``

**Method of Controller when user click Login with Github link**
```
public function doReservation($provider)
    {
        return Socialite::driver($provider)
            ->with(['event_slug' => 'foobar' ])
            ->redirect();
    }
```

**Method of Controller when Github do callback**
```
use Illuminate\Http\Request;

public function handleProviderCallback($provider, Request $request)
{
// I would like to test what I got from callback so I use `dd()`
dd($request);
// But, the result I get only `code` and `state`. I don't get `event_slug`
}
```
What I wish that user success login with Github then I use `event_slug` value to register meetup for the user and then redirect them to the home page.

**Comment by qWici** [comment]
@satyakresna thats mean - you can add optional parameters for the request to social network. This feature was added in 5880e68 commit and later method was renamed to `with()`

**Comment by satyakresna** [comment]
@qWici, I have implemented optional parameters by using `with()` method when Socialite direct to provider OAuth based on this code
```
public function doReservation($provider)
    {
        return Socialite::driver($provider)
            ->with(['event_slug' => 'foobar' ]) // this one.
            ->redirect();
    }
```

But, I don't get the value of `event_slug` when Socialite callback in Github and only get the value of `state` and `code`

```
use Illuminate\Http\Request;

public function handleProviderCallback($provider, Request $request)
{
// But, the result I get only value of `code` and `state`. I don't get `event_slug` value.
dd($request);
}
```

That's why I'm curious is it possible I can add my own optional parameters like `event_slug` and then get the value of `event_slug` in callback method?

**Comment by qWici** [comment]
@satykresna with this method you add additional parameters for the authorization request. If social networks return your parameters - you was get them.

**Comment by qWici** [comment]
@satyakresna  with this method you add additional parameters ONLY for the authorization request. If social networks return your parameters - you was get them.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by satyakresna** [comment]
Noted, thanks @driesvints

**Comment by satyakresna** [comment]
Hi, I found the solution. According to [Github OAuth Docs](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls), it tells that I can modify Redirect URL by add subdirectory after callback URL. Oh, I also found a good answer in SO related about [this topic](https://stackoverflow.com/questions/35942009/github-oauth-multiple-authorization-callback-url)

Example:

**My Github Callback URL registered on Oauth Apps**
```http://example.com/login/github/callback```

**My custom callback. So, I can make user registered after they log in with Github via Socialite**
```http://example.com/login/github/callback/events/my-event-name```

Next, I set custom redirect_uri when user press register event by login with Github in this method:

```
public function doReservation()
    {
        // Get current event
        $event = Event::with('reservations')
        ->where('published', 1)
        ->orderBy('created_at', 'desc')
        ->first();
        return Socialite::driver('github')
            ->redirectUrl(env('GITHUB_CALLBACK_URL')."?event_slug={$event->slug}")
            ->with([
                'redirect_uri' => url("/login/github/callback{$event->path()}")
            ])
            ->redirect();
    }
```

Then, in my route web, I set optional parameters on callback route
```Route::get('login/github/callback/{events?}/{event_slug?}', 'AuthController@handleProviderCallback');```

In `handleProviderCallback` method, we implement like this:

```
public function handleProviderCallback($events = null, $event_slug = null)
    {
        try {
            $user = Socialite::driver('github')->user();
        } catch (\Exception $e) {
            return redirect()->back()->withErrors('Whoops, something errors');
        }

         Auth::login($user, true);

        // Check if event slug is exist then find the event based on slug
        if ($request->has('event_slug')) {
            $event = Event::where('slug', $request->event_slug)->first();
            // If event is exist then register user to meetup event
            if (!empty($event)) {
        if (!empty($events) && !empty($event_slug)) {
            $event = Event::where('slug', $event_slug)->first();
            // Check if event is exists and has not finished yet.
            if (!empty($event) && !$event->hasFinished()) {
                // Check if user doesn't register yet
                if ($event->reservations()->where('user_id', auth()->user()->id)->get()->isEmpty()) {
                    auth()->user()->reservation()->create([
                        'user_id' => auth()->user()->id,
                        'event_id' => $event->id
                    ]);
                }
            }
        }
        return redirect('/');
    }
```

Hope, it helps everyone who struggles on this problem.

**Comment by warddeboeck** [comment]
Hi,
Is this in anyway possible with Facebook, I can not seem to make it work.

**Comment by lubistick** [comment]
Hello.
I checked how it works with google and facebook in stateless API. Hope it works in your case too. U need use

`
public function doReservation($provider)
 {
    return Socialite::driver($provider)
        ->with(['state' => 'event_slug=foobar'])
        ->redirect();
}
`

To obtain event_slug in handleProviderCallback() do the following

`
public function handleProviderCallback(Request $request)
{
    $state = $request->input('state');
    parse_str($state, $result);
    dd($result['event_slug']);
}


`

**Comment by kdaniel21** [comment]
Thanks @lubistick, it worked for me, but after that Socialite throws an InvalidStateException. How did you overcome this?

**Comment by hamid159** [comment]
> Thanks @lubistick, it worked for me, but after that Socialite throws an InvalidStateException. How did you overcome this?

You have to disable state parameter verification throught `stateless` while fetching the user.
`$user = Socialite::driver($provider)->stateless()->user();`
