### ISSUE TITLE
please update facebook version to 3.3 at branch 2.0

### ISSUE THREAD

**Issue by nosun** [laravel/socialite#375]
Facebook Graph API v2.9  will reach the end of its 2-year lifetime on 22 July, 2019. 

Need to upgrade the version number of the api。

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
