### ISSUE TITLE
Coinbase not working in api v1

### ISSUE THREAD

**Issue by codemastersolucoes** [laravel/socialite#379]
- Socialite Version: 4.1.3
- Laravel Version: 5.8.18
- PHP Version: 7.3.6
- Database Driver & Version: mariaDB:10.4.5

### Description:
Provider Coinbase not working in api v1, when provider call the api, receive this error:

Client error: `GET https://api.coinbase.com/v1/users/self` resulted in a `404 Not Found` response: {"errors":[{"id":"not_found","message":"Not found"}]}

Changing the current address to new address(https://api.coinbase.com/v2/user) from the coinnbase api documentation, https://developers.coinbase.com/api/v2#oauth2-coinbase-connect, it's work, but the response obtained doesn't contain the format expected by the provider.

Response obtained from new api address:
array:2 [▼
  "data" => array:9 [▼
    "id" => "<user_id>"
    "name" => "<user_name>"
    "username" => null
    "profile_location" => null
    "profile_bio" => null
    "profile_url" => null
    "avatar_url" => "https://images.coinbase.com/avatar?h=5d20a1f0dc34e629fb849WIpwqZYoSKrEF1PdL%2BdoGu9fX8%2BSD1PbPvBFqAZ%0Ab6VH&s=128"
    "resource" => "user"
    "resource_path" => "/v2/users/<user_id>"
  ]
  "warnings" => array:1 [▼
    0 => array:3 [▼
      "id" => "missing_version"
      "message" => "Please supply API version (YYYY-MM-DD) as CB-VERSION header"
      "url" => "https://developers.coinbase.com/api#versioning"
    ]
  ]
]

**Comment by driesvints** [comment]
We don't support coinbase in Socialite.

**Comment by codemastersolucoes** [comment]
Ok, Thanks
