### ISSUE TITLE
Facebook no longer supports http

### ISSUE THREAD

**Issue by Adron55** [laravel/socialite#383]
I think it is good to mention that facebook no longer support http and users must use https in **FACEBOOK_URL** of environment file(.env). Otherwise , error keep going to showing at callback

**Comment by driesvints** [comment]
I think it's a given that you should try to use https always. If you really feel this should be noted feel free to attempt a pr to the docs. Thanks.

**Comment by Adron55** [comment]
I mean in the laravel doc written as http it can change i think and it is hard for who working first time with Socialite

**Comment by driesvints** [comment]
@Adron55 gotcha. Try a pr to see if it works. Otherwise I can help out.

**Comment by Adron55** [comment]
What do u mean with try a pr ?

**Comment by driesvints** [comment]
@Adron55 try a pull request to the documentation: https://github.com/laravel/docs

**Comment by Adron55** [comment]
Thanks . I tried adding little note in the documentation .
