### ISSUE TITLE
Use route for redirect URL

### ISSUE THREAD

**Issue by yakatz** [laravel/socialite#388]
I have general routes to allow easily adding Socialite providers:
```php
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('socialite.redirect');  
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('socialite.callback');
```

Because config is loaded before routes, it isn't possible to set the `redirect` option in `services.php` using something like `route('socialite.callback', ['provider' => 'google']),`.

My proposal is to allow setting a route name for Socialite and use that to create a default `redirect` if one isn't specified.

Something like this (although there isn't currently a simple way to get the provider name either?):
```php
    /**
     * Format the callback URL, resolving a relative URI if needed.
     *
     * @param  array  $config
     * @return string
     */
    protected function formatRedirectUrl(array $config)
    {
        $redirect = value($config['redirect']);
        if ( ! defined($redirect) ) {
            return $this->defaultRedirectUrl($config);
        }
        return Str::startsWith($redirect, '/')
                    ? $this->app['url']->to($redirect)
                    : $redirect;
    }

    /**
     * Get a default callback route.
     *
     * @param  array  $config
     * @return string
     */
    protected function defaultRedirectUrl(array $config)
    {
        $socialite_config = $this->app['config']['socialite'];
        $route = value($config['route']);
        if ($route) {
            return $this->app['url']->route($route, ['provider' => $config['provider'] ]);
        } else {
            throw new Exception();
        }
    }
```

**Comment by driesvints** [comment]
So this is basically an easier way instead of setting up the controller for routing? https://laravel.com/docs/5.8/socialite#routing

**Comment by yakatz** [comment]
No, this is substantially different. Right now you need to set the callback url in `serices.php` individually for each provider and there is no way to set it in the controller. Since you need to have a route for the callback anyway, this change would allow you to not need to specify the callback in the configuration.

**Comment by driesvints** [comment]
Feel free to send in a PR when you have some time.

**Comment by vijayq9** [comment]
Open vendor\laravel\socialite\src\SocialiteManager.php and  Replace
  protected function createFacebookDriver()
    {
         $config = $this->app['config']['services.facebook'];
          return $this->buildProvider(
            FacebookProvider::class, $config
        );
    }

      protected function createFacebookDriver()
    {
         $config = $this->app['config']['services.stripe.facebook'];
          return $this->buildProvider(
            FacebookProvider::class, $config
        );
    }

**Comment by vijayq9** [comment]
Than it is working

**Comment by yakatz** [comment]
@vijayq9 Can you explain how this is related to my issue? I didn't say anything about Facebook.

**Comment by driesvints** [comment]
Since Taylor rejected the PR I'm afraid we won't be providing support for this, sorry.

**Comment by adwiv** [comment]
@yakatz I had the same requirement, and I agree that the redirect url should be optional in the config, however I found it is possible to use routes for redirect urls. There is a method `redirectUrl($url)` on the socialite provider that can be used to override the one stated in config. We need to override it in both the redirect method as well as in the callback for it to work properly.

To do what you asked for, you can start with setting empty redirect value in the `config/services.php`

    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect' => '',
    ],

Then in the LoginController

    private function socialiteProvider($provider)
    {
        $redirectUrl = route("login.callback", ['provider' => $provider]);
        return Socialite::driver($provider)->redirectUrl($redirectUrl);
    }

    public function redirectToProvider($provider)
    {
        return $this->socialiteProvider($provider)->redirect();
    }

    public function handleProviderCallback($provider)
    {
        $socialiteUser = $this->socialiteProvider($provider)->user();
        dd($socialiteUser);
    }

Ideally, you would limit the routes to the names of providers you actually implement instead of keeping it open. So only say `login/google` and `login/facebook` instead of `login/{provider}`

**Comment by yakatz** [comment]
@adwiv Thanks, but that doesn't seem to work for Google. You run into issue #382

**Comment by adwiv** [comment]
@yakatz That issue only arises if you want to use a different `client_id` instead of the one defined in the config file. The only way to do it is by overriding the request using the `with([..])` method which is unfortunately not implemented during the token verification phase.

However, if you just want to use a different callback url,  `redirectUrl` method works perfectly. The same is also mentioned in the workaround section of the issue you linked. I am using the code I shared in my app, so it certainly works with google.

**Comment by yakatz** [comment]
I don't know - I think that is what I am doing:

```php
class LoginController extends Controller
{
	........

	public function redirectToProvider($provider)
	{
		$redirectUrl = route("login.callback", ['provider' => $provider]);
		$driver = Socialite::driver($provider)->redirectUrl($redirectUrl);
		return $driver->redirect();
	 }

	public function handleProviderCallback($provider)
	{
		$user = Socialite::driver($provider)->user();

		$authUser = $this->findOrCreateUser($user, $provider);
		Auth::login($authUser, true);

		return redirect($this->redirectTo);
	}
}
```

**Comment by adwiv** [comment]
You need to set the redirectUrl in the `handleProviderCallback` too.

    $user = Socialite::driver($provider)->redirectUrl($redirectUrl)->user();

**Comment by BariqDharmawan** [comment]
You can use something like this in in config/service
```
'facebook' => [
        'client_id'     => env('FB_ID'),
        'client_secret' => env('FB_SECRET'),
        'redirect'      => '/auth/facebook/callback',
    ],
```

I'd already use that, and it's working. So basically you don't need setup your route anymore when move the project from local to production

**Comment by yakatz** [comment]
> You can use something like this in in config/service
> 
> ```
> 'facebook' => [
>         'client_id'     => env('FB_ID'),
>         'client_secret' => env('FB_SECRET'),
>         'redirect'      => '/auth/facebook/callback',
>     ],
> ```
> 
> I'd already use that, and it's working. So basically you don't need setup your route anymore when move the project from local to production

I don't think you understand this issue. The point is to allow setting the redirect URL dynamically using the available routes.

**Comment by mehrancodes** [comment]
> I don't know - I think that is what I am doing:
> 
> ```
> class LoginController extends Controller
> {
> 	........
> 
> 	public function redirectToProvider($provider)
> 	{
> 		$redirectUrl = route("login.callback", ['provider' => $provider]);
> 		$driver = Socialite::driver($provider)->redirectUrl($redirectUrl);
> 		return $driver->redirect();
> 	 }
> 
> 	public function handleProviderCallback($provider)
> 	{
> 		$user = Socialite::driver($provider)->user();
> 
> 		$authUser = $this->findOrCreateUser($user, $provider);
> 		Auth::login($authUser, true);
> 
> 		return redirect($this->redirectTo);
> 	}
> }
> ```

it worked!
