### ISSUE TITLE
Get username (nickname) and other extended profile data back from Linkedin using Laravel Socialite

### ISSUE THREAD

**Issue by connecteev** [laravel/socialite#400]
- Socialite Version: "^4.0"
- Laravel Version: 5.8 / 6.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.8 / 8.0

How can I request extended data to be returned back from Linkedin? I am interested in the Linkedin profile data that includes:
- Username
- Location
- Current TItle
- Current Company etc

I'm using the latest version of [Laravel Socialite](https://laravel.com/docs/6.x/socialite#retrieving-user-details) to log a user into:
- Github
- Google
- Linkedin

I am able to get the basic user details (email, id) from Linkedin.

I've already read the docs, this is what I am doing to request the appropriate scopes:
```
        switch($service) {
            case 'github':
                // https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/
                $scopesArray = ['user:email', 'read:user']; // Socialite default: ['user:email']
                break;
            case 'google':
                // https://developers.google.com/identity/protocols/googlescopes#google_sign-in
                $scopesArray = ['openid', 'profile', 'email']; // Socialite default: ['openid', 'profile', 'email']
                break;
            case 'linkedin':
                // https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin#authenticating-members
                $scopesArray = ['r_liteprofile', 'r_emailaddress']; // Socialite default: ['r_liteprofile', 'r_emailaddress']
                break;
            default:
                return response(['error' => 'Yo! Invalid service, ' . $service . ' is not supported.'], Response::HTTP_BAD_REQUEST);
                break;
        }
        Socialite::driver($service)->setScopes($scopesArray);
```

```
            $socialiteUser = Socialite::driver($service)->userFromToken($request->providerToken);
            $socialUsername = $socialiteUser->getNickname();
```

According to https://github.com/laravel/socialite/issues/384#issuecomment-519518094, for the new Linkedin API we had to downgrade the r_basicprofile scope to the r_liteprofile scope. 
Can we fix this so we can get this data back?

**Comment by driesvints** [comment]
Gonna close this in favor of the issue linked above.

**Comment by connecteev** [comment]
@driesvints #384 has already been closed, leaving no open issues..so this is also going to be forgotten.

**Comment by driesvints** [comment]
I meant https://github.com/laravel/socialite/issues/368
