### ISSUE TITLE
Make getAuthUrl() public so first-party client can retrieve authorization URL over API

### ISSUE THREAD

**Issue by connecteev** [laravel/socialite#401]
- Socialite Version: "^4.0"
- Laravel Version: 5.8 / 6.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.8 / 8.0

I am trying to implement first-party social login over APIs using Laravel Socialite
// This is the end-to-end flow we're trying to get right:
1. [User] Clicks login
2. [Frontend] makes an Axios / XHR call to backend to get AuthorizationURL
3. [Frontend] forwards to provider's authorize URL
Continue with rest of oAuth flow:
4. [3rd party Provider] forwards to callback URL with code (frontend)
5. [Frontend] makes post request with code -> backend
6. [Backend] verifies code and exchanges it for token from provider
7. [Backend] exchanges provider token for Passport token
8. [Backend] responds with XHR to frontend with Passport access_token in body
9. [Frontend] sets cookie and logs in user

We're unable to do step 2 because getAuthUrl() in each of the providers (AbstractProvider, GithubProvider, GoogleProvider, LinkedinProvider, etc) is protected, not public. Can this be changed?
```
    abstract protected function getAuthUrl($state);
```
Is there a better approach? What are we missing?

**Comment by driesvints** [comment]
Socialite isn't really meant to work like this in the front-end. It's in the first place a back-end implementation. If you need this, consider authenticating through API calls.

**Comment by connecteev** [comment]
> If you need this, consider authenticating through API calls.

@driesvints that's exactly what I am trying to do here. Without this API, it's impossible.

**Comment by driesvints** [comment]
@connecteev I meant directly without Socialite.

**Comment by OmdaMukhtar** [comment]
@driesvints which means socialist will not do it for me right now.
