### ISSUE TITLE
GitLab provider requests all scopes by default, which can be too permissive

### ISSUE THREAD

**Issue by Calinou** [laravel/socialite#402]
- Socialite Version: 4.2.0
- Laravel Version: 6.4.0
- PHP Version: 7.3.10
- Database Driver & Version: MariaDB 10.3.17

### Description:

The GitLab provider requests all scopes by default, which grants very broad permissions if the application was created with the default settings. In contrast, the GitHub provider only requests the minimum required to authenticate the user (`user:email`).

To prevent this, only the `read_user` scope should be requested by default.

### Steps To Reproduce:

**Edit:** It appears the behavior depends on the scopes you grant to the application when creating it on GitLab. If you don't check any of the scope  checkboxes, all of them will implicitly be checked when you add the application, which causes the behavior described above. I guess it still makes sense to restrict the scope asked by default.

If you only allow the `read_user` scope on the GitLab application, you *must* request the scope explicitly by name, otherwise GitLab will return an error:

```text
The requested scope is invalid, unknown, or malformed.
```

This can be worked around by explicitly overriding the scope when authenticating the user with GitLab:

```php
    /**
     * Redirect the user to the OAuth2 provider's authentication page.
     */
    public function redirectToProvider(string $provider): RedirectResponse
    {
        if ($provider === 'gitlab') {
            // Only request the `read_user` scope if authenticating with GitLab
            return Socialite::driver($provider)->scopes(['read_user'])->redirect();
        }

        return Socialite::driver($provider)->redirect();
    }
```

I can look into submitting a pull request if this change is desired.

**Comment by driesvints** [comment]
Will all fields for the `mapUserToObject` method be returned for this scope? Can you link to some documentation?

This at the least would have to go to master.

**Comment by Calinou** [comment]
Reading the [GitlabProvider's `mapUserToObject` function](https://github.com/laravel/socialite/blob/ecc3ccfdcbbcee9e19468539985f0d0fddd4dbde/src/Two/GitlabProvider.php#L40-L49), it seems I get all the required fields (tested by dumping the user after getting them from the provider):

```text
Laravel\Socialite\Two\User^ {#374
  ...
  +id: -snip-
  +nickname: "-snip-"
  +name: "-snip-"
  +email: "-snip-"
  +avatar: "-snip-"
  +user: array:31 [
    "id" => -snip-
    "name" => "-snip-"
    "username" => "-snip-"
    ...
    "avatar_url" => "-snip-"
    ...
    "email" => "-snip-"
    ...
  ]
}
```

**Comment by driesvints** [comment]
I think changing the default is okay. People can overwrite it with scopes. Feel free to send a PR to master.

**Comment by derekmd** [comment]
@driesvints With the Oct 28, 2019 PR merged, it looks like this issue can be closed?

**Comment by driesvints** [comment]
@derekmd good catch, thanks.
