### ISSUE TITLE
Upgrade Facebook Graph API version

### ISSUE THREAD

**Issue by nicocucuzza** [laravel/socialite#405]
- Socialite Version: 4.2
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
Facebook Graph API version is hardcoded to v3.0

`src/Two/FacebookProvider.php`
```php
/**
     * The Graph API version for the request.
     *
     * @var string
     */
    protected $version = 'v3.0';
```

That Graph version is from May 2018 and will be no longer available in 7 months. Plus, the version parameter is not configurable in the library.

**Comment by driesvints** [comment]
Does updating the version break existing apps in any way?

**Comment by brandonburkett** [comment]
@driesvints I have updated to 3.3 (via facebook's API version drop down, back in the thread for #364 ) and it worked with socialite pinned at 3.0... but my use case is very simple w/ facebook default / no approval login app.

**Comment by driesvints** [comment]
Fixed in https://github.com/laravel/socialite/pull/408
