### ISSUE TITLE
Feature Request: Please add Firebase Authentication support. 

### ISSUE THREAD

**Issue by wemersonrv** [laravel/socialite#406]
Hello.

Please add Firebase Authentication support. 

A large number of mobile apps are built using firebase as the authentication provider. And by using laravel to build administrative dashboards for these applications, we get great productivity; however did not find how to authenticate mobile users in the panel using the same auth source as mobile version.

**Comment by driesvints** [comment]
We're currently not using Firebase in our own products so we're probably not going to add this natively in Socialite sorry. Socialite is pretty extensible. Have a look, for example, at https://socialiteproviders.netlify.com/ to see how you can extend with a custom provider.

**Comment by ankurk91** [comment]
https://medium.com/firebase-developers/how-to-link-google-firebase-auth-and-laravel-passport-users-244b73567594
