### ISSUE TITLE
Class socialite does not exist

### ISSUE THREAD

**Issue by thewebartisan7** [laravel/socialite#409]
- Socialite Version: 4.3
- Laravel Version: 5.8
- PHP Version: 7.x

### Description:

Socialite is installed and I add in config/app.php the Service Provider and as alias the Facade, like below:

```php
    'providers' => [
        Laravel\Socialite\SocialiteServiceProvider::class,
    ],
    
    'aliases' => [
        'Socialite' => Laravel\Socialite\Facades\Socialite::class
    ],
```

But should be already loded the provider and alias since it's in composer?

```
        "laravel": {
            "providers": [
                "Laravel\\Socialite\\SocialiteServiceProvider"
            ],
            "aliases": {
                "Socialite": "Laravel\\Socialite\\Facades\\Socialite"
            }
        }
```
I try also without including in config/app.php but it's the same.

In controller I add `use Socialite;`

I try also `composer dump-autoload` and php `artisan cache:clear` but nothing, the class suddenly Socialite is not found.

Even in cached file I see that it's correctly included the provider and facade:

<img width="675" alt="Screenshot 2019-11-24 at 13 48 23" src="https://user-images.githubusercontent.com/57477934/69494953-c7b18b80-0ec1-11ea-8501-d3c8b7833eb9.png">

What I missing?

Thank You!

**Comment by thewebartisan7** [comment]
Fixed! It was something wrong in my application.

**Comment by hao41815w** [comment]
How did you fix that?

**Comment by Wulfheart** [comment]
Still interested how this could be solved?

**Comment by ronimondal** [comment]
same issue

**Comment by angelorubin** [comment]
I have same problem (2024), anyone else?
