### ISSUE TITLE
Is stateless available for Twitter?

### ISSUE THREAD

**Issue by alvirbismonte** [laravel/socialite#415]
I am building a Laravel API and would like to apply stateless for Twitter but unable to do it since it returns an error that stateless method is not available for TwitterProvider class. Is their a way to do this? Just to add, FB and Google works perfectly fine and I'm able to implement it. Thank you for the responses.

**Comment by driesvints** [comment]
The Twitter integration makes use of OAuth 1 so it can act on behalf of the user in order to make user actions against the Twitter API. Therefor it cannot be stateless. 

https://developer.twitter.com/en/docs/basics/authentication/overview/oauth

I'll update the docs with this.

**Comment by staqd** [comment]
https://medium.com/@favoriabs/twitter-stateless-social-login-sign-up-eea73bc3bb1d
package website: https://twitteroauth.com/

**Comment by abdulqadeer1999** [comment]
ZX
