### ISSUE TITLE
(maybe) Google oauth addon domain issue 

### ISSUE THREAD

**Issue by vk011** [laravel/socialite#416]
- Socialite Version: 4.1
- Laravel Version: 5.8
- PHP Version: 7.2

Hi, me again, the https://github.com/laravel/socialite/issues/389 guy , I might have new information.

To recap, I get an `InvalidStateException` when trying to log in via Google (Facebook works fine), however if I comment out `profile` from the scopes array then it works, but obviously without the profile information.

The website where I am using socialite is actually an **addon** domain (I actually tested the website locally and google login works fine with profile scope,), so -
Is it at all possible that socialite's google oauth implementation might have an issue with addon domains?

I cannot see any other reason for it not working for me other than the website using an addon domain (again, locally it works with the profile scope as well).

I reported this issue here https://github.com/googleapis/google-api-php-client and they said `Socialite appears to implement their own OAuth flow, not relying on the implementations provided by Google. `

So again, is there any possibility that the addon domain is the issue?

**Comment by driesvints** [comment]
Socialite works just fine for domains and subdomains. I have no idea what an addon domain even is. You might have more luck asking this on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
