### ISSUE TITLE
[Twitter-Custom-Config] Missing client credentials key [identifier] from options.

### ISSUE THREAD

**Issue by KinG-InFeT** [laravel/socialite#419]
Hi,
i try redirect with custom config for twitter driver, but not wok:
my code is:
```
$config = getconfig($webiste_setting, $service);

        $clientId = $config['client_id'];
        $clientSecret = $config['client_secret'];
        $redirectUrl = $config['redirect'];
        $additionalProviderConfig = [];
        
        $config = new \SocialiteProviders\Manager\Config($clientId, $clientSecret, $redirectUrl, $additionalProviderConfig);

        return Socialite::with($service)->setConfig($config)->redirect();
```
into

```
protected function buildOAuth1Provider(SocialiteManager $socialite, $providerClass, $providerName, $oauth1Server)
```

method (**SocialiteWasCalled** file) the config is null.

All other driver work fine (Facebook, google and linkedin).

Laravel 6.x and "laravel/socialite": "^4.2",

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by KinG-InFeT** [comment]
hi,
yes but this is a not a aks, this is a problem for twitter driver

**Comment by KinG-InFeT** [comment]
i created a Thread: https://laravel.io/forum/socialite-twitter-missing-client-credentials-key-identifier

**Comment by quanengineering** [comment]
I also had this issue.

**Comment by roozeec** [comment]
Hi, I have same problem on another driver : https://github.com/laravel/socialite/issues/503
Did you solve your problem ?

**Comment by KinG-InFeT** [comment]
really bad support

**Comment by roozeec** [comment]
In the microsoft graph provider , i added this function which get the session data ::


    public function getAccessTokenResponse($code)
    {
        if (session('clientId')) {
            $this->clientId = session('clientId');
            $this->clientSecret = session('clientSecret');
            $this->redirectUrl = session('redirectUrl');
        }
        $response = $this->getHttpClient()->post($this->getTokenUrl(), [
            'headers' => ['Accept' => 'application/json'],
            'form_params' => $this->getTokenFields($code),
        ]);
        return json_decode($response->getBody(), true);
    }

And before calling : 


session(['clientId' => $clientId,'clientSecret'=>$clientSecret,'redirectUrl'=>$redirectUrl]);
$additionalProviderConfig = ['tenant_id' => $credential['tenant']];
$mycfg = new \SocialiteProviders\Manager\Config($clientId, $clientSecret, $redirectUrl,$additionalProviderConfig);
return Socialite::driver($auth_mode)->setTenantId($credential['tenant'])->setConfig($mycfg)->redirect();

Not sure , it is the best solution, but it works ...

**Comment by KinG-InFeT** [comment]
thank you for the code snippet
