### ISSUE TITLE
Upgrade guide is giving the wrong PHP version

### ISSUE THREAD

**Issue by thanedar** [laravel/socialite#426]
Currently the upgrade guide mentions that Socialite requires PHP version >= 7.1.3. So I was trying to update Socialite to 4.0 along with the Laravel upgrade to 5.6 (which is the first version that requires 7.1.3). The composer upgrade fails as `symfony/http` used by Socialite requires PHP version >= 7.2.0 which is only required at Laravel 6.x

So the upgrade guide needs to be updated to say that Socialite 4.0 can be used with PHP version >= 7.2.0.

**Comment by driesvints** [comment]
v7.2.0 is the minimum version of Laravel v6.0, not Socialite. Socialite still supports older Laravel versions so it needs to have a lower minimum.

**Comment by thanedar** [comment]
I understand that Socialite supports older Laravel versions. But Socialite uses `illuminate/http` (by mistake I had written `symfony/http` earlier) and that package is 7.2 and above only (https://packagist.org/packages/illuminate/http#v6.0.0). So Socialite 4.0 can only be installed on any older Laravel versions where PHP version is ^7.2.0. I can provide the composer error log if you need to verify.

**Comment by driesvints** [comment]
It can be installed from v5.7 until v7.0-dev: https://github.com/laravel/socialite/blob/4.0/composer.json#L21

**Comment by thanedar** [comment]
Yes, just checked and looks like 5.7 is the minimum while I was trying on 5.6
