### ISSUE TITLE
Facebook Email always null

### ISSUE THREAD

**Issue by REPTILEHAUS** [laravel/socialite#435]
- Socialite Version: laravel/socialite": "^3.0",
- Laravel Version: Laravel Framework 5.7.5
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:

Email always returning null from facebook

Im using my own facebook account which was registered using an email address - so facebook have my email - some folks say that this is expected behaviour as you can sign up with a phone which I did not

### Steps To Reproduce:

dd( Socialite::driver('facebook')->stateless()->user() );

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by AmrAkram1999N** [comment]
I have the same problem, did you have any **solution**????
