### ISSUE TITLE
iignatov / LightOpenID is abandoned, uses PHP5s get_magic_quotes_gpc

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/socialite#441]
- Socialite Version: ^4.1
- Laravel Version: ^7
- PHP Version: ^7.4
- Database Driver & Version: MySQL 5.7

### Description:

Better explained here: https://github.com/iignatov/LightOpenID/issues/20 

### Steps To Reproduce:

- Install socialite
- install openid provider (steam, for example)
- try to grab credentials
- error ` $params['openid.' . $item] = function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc() ? stripslashes($value) : $value; "Function get_magic_quotes_gpc() is deprecated"`

**Comment by driesvints** [comment]
We don't support openid.
