### ISSUE TITLE
Yandex OAuth Issue

### ISSUE THREAD

**Issue by flatdragon** [laravel/socialite#445]
- Socialite Version: 4.3.2
- Laravel Version: 6.5.1
- PHP Version: 7.2.10
- Database Driver & Version: MySQL 5.8

### Description:
There is an issue with SocialiteProviders/Yandex package and Yandex OAuth, that comes maybe few days ago (customer contact me today about issue).

The problem of issue is that Socialite package doesn't filter empty values of $fields array. As a result there is an empty "scope" parameter in URL. In my case, it generates URL like this one:
```
https://oauth.yandex.ru/authorize?client_id={client_id}&redirect_uri={redirect_url}&scope=&response_type={response_type}&state={state}
```

For temporary fix the issue I've placed this line:
```php
$fields = array_filter($fields);
```

Into Laravel\Socialite\Two\AbstractProvider::getCodeFields method:
```php
protected function getCodeFields($state = null)
{
    $fields = [
        'client_id' => $this->clientId,
        'redirect_uri' => $this->redirectUrl,
        'scope' => $this->formatScopes($this->getScopes(), $this->scopeSeparator),
        'response_type' => 'code',
    ];

    if ($this->usesState()) {
        $fields['state'] = $state;
    }

    $fields = array_filter($fields);

    return array_merge($fields, $this->parameters);
}
```

### Steps To Reproduce:
1) Clone repo: git clone https://github.com/flatdragon/socialite-yandex-issue.git
2) Run: composer install
3) Run: php artisan serve
4) Open URL: http://localhost:8000
5) Press "Login with Yandex" button.
6) After you got an error, check URL and remove "scope" parameter, then press "Enter" and you will see correct result.

### P.S.
You can checkout any changes of fresh laravel install by checking last commit: https://github.com/flatdragon/socialite-yandex-issue/commit/7e9836c2a51f74845a3b2b698bb2807f326ecc8d

**Comment by driesvints** [comment]
We don't maintain this.
