### ISSUE TITLE
Cannot redirect to the home page after entering google account credentials

### ISSUE THREAD

**Issue by VinceSanityyy** [laravel/socialite#452]
- Socialite Version:   `"laravel/socialite": "^4.4"`
- Laravel Version: ` "laravel/framework": "^6.2"`
- PHP Version: `7.3.18`
- Database Driver & Version: MySQL

### Description:
I have a laravel project that uses google to login. I am using socialite package from laravel. I can save the user's info in my database after they confirm in the google auth screen, but after that it will redirect to login always. It seems the `Auth::login($user)` is not working. Did I miss something?

Here is my controller code
```
public function redirectToProvider()
    {
    return Socialite::driver('google')->redirect();
    }

 
  public function handleProviderCallback()
    {
        try {
            $user = Socialite::driver('google')->user();
        } catch (\Exception $e) {
            return redirect('/login');
        }
   
        $existingUser = User::where('email', $user->email)->first();
        if($existingUser){
            //login the user
            \Auth::login($existingUser,true);
            return redirect('/home');        
        } else {
            // create a new user
            $newUser                  = new User;
            $newUser->name            = $user->name;
            $newUser->email           = $user->email;
            $newUser->google_id       = $user->id;
            $newUser->avatar          = $user->avatar;
            $newUser->avatar_original = $user->avatar_original;
            $newUser->save();

            \Auth::login($newUser,true);
        }
        return redirect('/home');
    }
```
Routes
```
Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');
```

Also when i check the network. the `/login` path is written as response 302.
![image](https://user-images.githubusercontent.com/38340124/85439573-b8153500-b5bf-11ea-844e-804457925b27.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
