### ISSUE TITLE
composer require guzzlehttp/guzzle 

### ISSUE THREAD

**Issue by fmym** [laravel/socialite#453]
- Socialite Version: 4.4.1
- Laravel Version: 7.18.0
- PHP Version: 7.4.4
- Database Driver & Version:

### Description:
`composer require guzzlehttp/guzzle`

```
...
Your requirements could not be resolved to an installable set of packages
Installation request for league/oauth1-client (locked at 1.7.0) -> satisfiable by league/oauth1-client[1.7.0].
...
```

**Comment by GrahamCampbell** [comment]
`composer require guzzlehttp/guzzle:^6.5`

**Comment by fmym** [comment]
> `composer require guzzlehttp/guzzle:^6.5`

Hope to get on 7.0 soon.

**Comment by driesvints** [comment]
Please open an issue on the league library. We don't maintain this package.
