### ISSUE TITLE
LinkedIn Login A required parameter "code" is missing

### ISSUE THREAD

**Issue by indiandeveloper2020** [laravel/socialite#454]
- Socialite Version: ^4.4
- Laravel Version: 7
- PHP Version: 7.4
- Database Driver & Version:

### Description:
When ever I try to login with linkedin, I get following error.
`"class": "GuzzleHttp\\Exception\\ClientException",
    "message": "Client error: `POST https://www.linkedin.com/oauth/v2/accessToken` resulted in a `400 Bad Request` response:\n{\"error\":\"invalid_request\",\"error_description\":\"A required parameter \\\"code\\\" is missing\"}\n",
    "code": 400,`

I have added the product `Sign In with LinkedIn` to LinkedIn App, but its show 
`OAuth 2.0 scopes
Permissions your app can request from users
No permissions added` 
Do I update something in LinkedIn App ?

**Comment by indiandeveloper2020** [comment]
This is working with other linkedin account other than Admin.

**Comment by laiba-tariq78** [comment]
> This is working with other linkedin account other than Admin.

I tried using 2 different LinkedIn accounts, but it still not working...
