### ISSUE TITLE
linkedin authentication does not work

### ISSUE THREAD

**Issue by Enmaboya** [laravel/socialite#456]
- Socialite Version: 4.4
- Laravel Version:  7.19.1
- PHP Version: PHP 7.4.3 
- Database Driver & Version: mysql  Ver 8.0.20-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Description:
there's been a login error:
Client error: `POST https://www.linkedin.com/oauth/v2/accessToken` resulted in a `400 Bad Request` response: {"error":"invalid_request","error_description":"A required parameter \"code\" is missing"}

in 'target url' itself, there is no 'code'.

### Steps To Reproduce:
1) create linkedin app
2) add callback url in linkedin app
3) login with socialite

**Comment by driesvints** [comment]
I've tested this recently and I could use the linkedin driver just fine. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
Thanks.

**Comment by Radiergummi** [comment]
If anyone ends up here: The error keeps bubbling up on our production Sentry, so I dug into it. Apparently, it occurs (with other providers too!) if users abort a signin attempt, choose to cancel the authorisation, and so on; that is, they choose a cancel action on the authorization form _of the provider_.  
Once they are redirected to your application's callback endpoint, the request URL doesn't look like you would expect:
```
https://foo.bar/auth/callback/linkedin?code=w8fh29guh1klrjf1...&state=213uf9h32ei2u...
```
but like this instead:
```
https://foo.bar/auth/callback/linkedin?error=user_cancelled_authorize&error_description=The%20user%20cancelled%20the%20authorization&state=213uf9h32ei2u...
```

This means there's no `code` query parameter in the URL, but an error code instead. The Laravel documentation doesn't go into this, but you'll need to handle this error _before passing control to Socialite_!
The documentation shows the following example for the callback route:
```php
Route::get('/auth/callback', function () {
    $user = Socialite::driver('github')->user();
 
    // $user->token
});
```

Extend it to the following:
```php
Route::get('/auth/callback', function (Request $request) {
    if ($request->has('error')) {
        return redirect()->route('login_route')->withError([
            'auth' => $request->input('error_description')
                ?? $request->input('error')
        ]);
    }

    $user = Socialite::driver('github')->user();
 
    // $user->token
});
```

@driesvints I think it would be great to denote at last a paragraph on error handling in the Socialite docs -- even better, integrate handling for those (standardised) query parameter errors to the library. This shouldn't be a userland concern.

**Comment by driesvints** [comment]
Thanks @Radiergummi for those insights. Adding it to the docs will be the short term solution here. I'm not sure we can integrate it into Socialite but if you see a way we'd appreciate a PR.
