### ISSUE TITLE
Driver [apple] not supported. error for socialiteproviders/apple

### ISSUE THREAD

**Issue by vishalkul** [laravel/socialite#457]
- Socialite Version: 4.x
- SocialiteProvider/Apple Version: 3.x
- Lumen Version: 7.x
- PHP Version: 7.2

### Steps To Reproduce:

- Install Lumen : composer global require "laravel/lumen-installer"

- Create Project : composer create-project --prefer-dist laravel/lumen lumen2

- Install socialiteprovide/apple : composer require socialiteproviders/apple

- And other steps given in [https://socialiteproviders.netlify.app/providers/apple.html](https://socialiteproviders.netlify.app/providers/apple.html) 

Kindly correct me if I am going in wrong direction or this is not a bug.

**Comment by driesvints** [comment]
Please open an issue on the socialite providers repo.

**Comment by Keanhor2** [comment]
Hi brother ! 
currently I do social login apple, but  got error : "Driver [apple] not supported."
