### ISSUE TITLE
Driver [apple] not supported.

### ISSUE THREAD

**Issue by vishalkul** [laravel/socialite#458]
- Socialite Version: 4.x
- SocialiteProvider/Apple Version: 3.x
- Lumen Version: 7.x
- PHP Version: 7.2

### Steps To Reproduce:

- Install Lumen : composer global require "laravel/lumen-installer"

- Create Project : composer create-project --prefer-dist laravel/lumen lumen2

- Install socialiteprovide/apple : composer require socialiteproviders/apple

- And other steps given in [https://socialiteproviders.netlify.app/providers/apple.html](https://socialiteproviders.netlify.app/providers/apple.html) 

Kindly correct me if I am going in wrong direction or this is not a bug.

**Comment by driesvints** [comment]
Please open an issue on the socialite providers repo like I asked you in the previous issue.
