### ISSUE TITLE
Composer update issue - outdated dependency?

### ISSUE THREAD

**Issue by cchacholiades** [laravel/socialite#459]
- Socialite Version: ^4.4.1
- Laravel Version: ^7.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:

When I do:

`php composer update` 

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### composer why:
```
php composer.phar why guzzle/guzzle
league/oauth1-client  1.6.2  requires  guzzle/guzzle (3.*)

php composer.phar why league/oauth1-client
laravel/socialite  v4.4.1  requires  league/oauth1-client (^1.0)
```

**Comment by driesvints** [comment]
Please open an issue on `league/oauth1-client` which needs to do a release for Guzzle 7

**Comment by GrahamCampbell** [comment]
If you manually require guzzle 6 in your app, you will avoid guzzle 3 being pulled in.

**Comment by cchacholiades** [comment]
Thank you for your response @driesvints. 
@GrahamCampbell I am not sure so better if I ask: 

Socialite's latest version [requires](https://github.com/laravel/socialite/blob/v4.4.1/composer.json) `league/oauth1-client :  ^1.0`  

league/oauth1-client has an updated version that made the transition to guzzlehttp/guzzle (https://github.com/thephpleague/oauth1-client/tree/1.7.0) is this version being pulled in to Socialite?

**Comment by driesvints** [comment]
> is this version being pulled in to Socialite?

Yes: https://github.com/laravel/socialite/blob/4.0/composer.json#L23

**Comment by cchacholiades** [comment]
`php composer.phar why guzzle/guzzle` shows that I am using `league/oauth1-client  1.6.2`. How? 

The fix is included in  `league/oauth1-client  1.7`..

**Comment by driesvints** [comment]
@cchacholiades just throw away your vendor dir and composer.lock file and run composer install

**Comment by cchacholiades** [comment]
I did that, it did not work unfortunately. 

- I removed vendor + composer.lock file
- run 

```
php composer clearcache 
php composer install --no-dev --no-scripts
```

- same end result:

```
php composer.phar why guzzle/guzzle
league/oauth1-client  1.6.2  requires  guzzle/guzzle (3.*)

php composer.phar why league/oauth1-client
laravel/socialite  v4.4.1  requires  league/oauth1-client (^1.0)
```

**Comment by driesvints** [comment]
Like graham said you need to explicitly require guzzle 6 in your composer.json

**Comment by cchacholiades** [comment]
So with this `"guzzlehttp/guzzle": "^7.0"` I get: 

>Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

But this "guzzlehttp/guzzle": "^6.0" works.

**Comment by GrahamCampbell** [comment]
Yes, that is correct.

**Comment by GrahamCampbell** [comment]
Because by asking for Guzzle 7, you are preventing the installation of the newest league oauth1 package.

**Comment by shehi** [comment]
That is "newest", in quotes. In a nutshell, `league/oauth1-client` project is dead, and it doesn't support Guzzle-7 (check its composer.json file). For that reason, everything cascades towards downgrading and resolves by installing old Guzzle lib.
