### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by antonsmolko** [laravel/socialite#461]
- Socialite Version: 4.4.1
- Laravel Version: 7.25.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Hi! Firstly, thanks for you package!

When the executing command `composer update`, i noticed following output
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`
Searching for the reason returned the following result
![2020-08-19_12-20-41](https://user-images.githubusercontent.com/20865516/90616746-7ba83300-e216-11ea-98b7-e7b0d0407cc2.png)

**Comment by GrahamCampbell** [comment]
This happens because you have installed Guzzle 7. You need to downgrade to Guzzle 6.

**Comment by driesvints** [comment]
See answer by graham
