### ISSUE TITLE
Problem with league/oauth1-client

### ISSUE THREAD

**Issue by atiehmokhtari** [laravel/socialite#463]
it seems that there is something wrong with upgrading guzzlehttp and the socialite required package league/oauth1-client.
I just tried to upgrade my laravel to laravel 7.0  and also my socialite to 4.4 and guzzlehttp/guzzle package to 7.0 the latest but the package of league/oath1-client downgrades from 1.7 to 1.6.2 which uses guzzle/guzzle instead of guzzlehttp/guzzle. so I am facing the deprecated warning
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

actually I have deleted composer.lock and vendor folder and then composer update but no help.
and also I had problem and error 500 while I wanted to login through google

**Comment by driesvints** [comment]
Please open an issue on the league repo.
