### ISSUE TITLE
Facebook graph API v8

### ISSUE THREAD

**Issue by anandagrawal84** [laravel/socialite#477]
Is there a plan to upgrade the Facebook provider to support latest facebook graph api that is v8

**Comment by driesvints** [comment]
You can already use `usingGraphVersion`. Is there anything specific not working for you?

**Comment by samfrm** [comment]
> You can already use `usingGraphVersion`. Is there anything specific not working for you?

Maybe wanted to ask if it needs any update to support this?

**Changes to tokenless access for User Picture and FB/IG OEmbed endpoints:**
https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8

**Comment by driesvints** [comment]
@samfrm can you explain a bit more? Is this a request for new features?

**Comment by samfrm** [comment]
@driesvints  It's about facebook's new update on that they will force developers to provide app token to get user's public profile picture. But I am not sure this will affect any parts of socialite.

**Comment by driesvints** [comment]
Would be willing to accept a PR to update the needed bits. Best be sent to master if breaking.
