### ISSUE TITLE
Facebook login Invalid appsecret_proof provided in the API argument

### ISSUE THREAD

**Issue by Munkhdemberel** [laravel/socialite#478]
- Socialite Version: 5.x-dev or 6.x-dev
- Laravel Version: 7.20.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:

First of all thank you for library.
I am using FB login functions of socialite and it was working fine yesterday.
But is giving error from today suddenly and have no idea why this error message is occurred.
Please help on this issue?

**Comment by driesvints** [comment]
Are you just using a plain setup of the Facebook driver or did you modify anything from the base install? Please share some code.

**Comment by driesvints** [comment]
Also please share your exact Socialite version where you're experiencing this.

**Comment by Munkhdemberel** [comment]
@driesvints Thank you for your response! No I didn't change anything from base install. 
Giving error for below line only:  
 $FBUser = Socialite::driver('facebook')->userFromToken($request->input("sm_token"));

Please check below link:

[](https://stackoverflow.com/questions/64148971/why-facebook-socialite-login-not-working-suddenly?noredirect=1#comment113438317_64148971)

**Comment by driesvints** [comment]
Please share your socialite version.

**Comment by Munkhdemberel** [comment]
![ss1](https://user-images.githubusercontent.com/20177267/94783694-a1bd1780-03ff-11eb-9f1e-9b2942982758.PNG)
![ss2](https://user-images.githubusercontent.com/20177267/94783699-a386db00-03ff-11eb-8d23-4f38e5267184.PNG)

Sorry I couldn't detect specific version. Please see above uploaded images.

**Comment by Munkhdemberel** [comment]
@driesvints thank you for your rapid response and again appreciate for good library.
I am closing issue now and issue was more related with FB and resolved 15 mins before.
Again sorry for the mess.

https://developers.facebook.com/status/issues/817076795498952/
