### ISSUE TITLE
Facebook 403 Forbidden Missing Permissions

### ISSUE THREAD

**Issue by raditzfarhan** [laravel/socialite#479]
- Socialite Version: v5.0.1
- Laravel Version: 8.7.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7.24

### Description:
When using Facebook driver to login, received 403 Forbidden error on callback because of the following code below.

`Socialite::driver('facebook')->user()`

Exact error message as below:
```
{
  "error": {
    "message": "(#200) Missing Permissions",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AnDmOjgOB6O56X0cpM0y-rO"
  }
}
```

### Steps To Reproduce:
1. Install latest Laravel.
2. Install latest Laravel Socialite plugin.
3. Setup your redirect and callback routes and configure your Facebook app credentials.
4. Set driver as `facebook`.
5. Access the login/redirect URL to authenticate with Facebook.
6. On your callback, call `Socialite::driver('facebook')->user()`

**Comment by mathiasmoser** [comment]
we get the same error with Laravel 7.28.1 and socialite v.4.4.1

**Comment by mathiasmoser** [comment]
it seems that there is a permission problem with the requested fields (fields=name,email,gender,verified,link), if i manually remove gender and link from the fields i get a response from fb

**Comment by mathiasmoser** [comment]
as a workaround i removed the fields gender and link from the requested fields, because this permissions have be requested in the facebook app settings and also require separate review process:

**With these reduced fields the request will work again:**
Socialite::driver('facebook')->fields(['name', 'email', 'verified'])->userFromToken($accessToken)

**Comment by driesvints** [comment]
I want to investigate first why this is broken in the first place after having worked for so many years. Did Facebook update its API? The API is versioned so this would be a breaking change on their part? Seems unlikely.

**Comment by raditzfarhan** [comment]
@driesvints I believe so. Yesterday was still working fine.

**Comment by raditzfarhan** [comment]
> as a workaround i removed the fields gender and link from the requested fields, because this permissions have be requested in the facebook app settings and also require separate review process:
> 
> **With these reduced fields the request will work again:**
> Socialite::driver('facebook')->fields(['name', 'email', 'verified'])->userFromToken($accessToken)

Thanks @mathiasmoser your solution is working.

**Comment by Maxwellkurt0407** [comment]
> 'name', 'email', 'verified'

Good day, how do I apply this fix? I've been having the same problem as well

**Comment by driade** [comment]
I've got this error in two apps this morning (CET) - (Socialite and Hybridauth), and after having myself seen it failing, now it seems it's working. Could anyone confirm it works again without further modifications? Is it possible Facebook had fixed something on their side?

Thanks in advance.

**Comment by mathiasmoser** [comment]
yes i can confirm that it seems to work again without any modifications

**Comment by raditzfarhan** [comment]
Yes, seems like now it's working again. Looks like Facebook has fixed it on their side.

**Comment by driesvints** [comment]
Seems like a facebook issue indeed: https://developers.facebook.com/status/issues/817076795498952/
