### ISSUE TITLE
Add support for the OAuth 2.0 PKCE extension

### ISSUE THREAD

**Issue by aaronpk** [laravel/socialite#483]
Many OAuth providers support the [PKCE](https://oauth.net/2/pkce/) extension, so it would be great to see this added in the core OAuth 2 class so that it can be leveraged by providers.

While PKCE was originally created for native apps, it also protects against [authorization code injection](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16#section-4.5) even for web server apps that use a client secret.

How to implement:
* Generate a new random string and store it in the session similar to how Socialite currently [stores the `state`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L150) value. 
* Then generate a SHA256 hash of that string and include that in the [`getCodeFields`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L175) parameters. 
* Include the original random string in the [`getTokenFields`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L274) POST request.

**Comment by driesvints** [comment]
https://laravel.com/docs/8.x/passport#code-grant-pkce

**Comment by aaronpk** [comment]
That's a link to Passport. I'm talking about adding support as an OAuth client so that Socialite providers can use PKCE without having to write that code in each provider's extension.

**Comment by driesvints** [comment]
Ah wow sorry. Totally didn't see this was the Socialite repo. 

I'm not sure if that's needed though. Socialite is only for social authentication and isn't meant to authorize API's.

**Comment by aaronpk** [comment]
No worries.

PKCE isn't just about authorizing APIs, it's for any OAuth client regardless of what it's doing. Since Socialite is used to talk to many OAuth servers (even just for social authentication), the client should be doing PKCE wherever possible. I thought it would make the most sense to add this at the core rather than duplicate that work in every Socialite provider.

**Comment by driesvints** [comment]
Do all of the 1st party providers currently support this? What key does it need to be stored under?

**Comment by aaronpk** [comment]
Unfortunately the only one of the providers in this repo that supports it is Google. However many of the ones in the [SocialiteProviders](https://github.com/SocialiteProviders/Providers/tree/master/src) repo support it.

That said, any conformant OAuth server is supposed to not fail if the additional PKCE parameters are included (PKCE was designed to be backwards compatible), although I have seen at least one server error out anyway, so I wouldn't recommend always enabling PKCE.

The parameters are called `code_verifier` and `code_challenge`.

My thought is this:

In the [`redirect`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L146) method

```php
        if ($this->usesPKCE()) {
            $this->request->session()->put('code_verifier', $state = $this->getCodeVerifier());
        }
```

In [`getCodeFields`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L175)

```php
        if ($this->usesPKCE()) {
            $fields['code_challenge'] = $this->getCodeChallenge();
            $fields['code_challenge_method'] = $this->getCodeChallengeMethod();
        } 
```

New functions for PKCE

```php
protected function getCodeChallenge() {
    $verifier = $this->request->session()->pull('code_verifier');
    $hashed = hash('sha256', $verifier, true);
    return rtrim(strtr(base64_encode($hashed), '+/', '-_'), '='); // base64-URL-encoding
}

protected function getCodeChallengeMethod() {
    return 'S256';
}
```

Then [`getTokenFields`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L274) becomes

```php
    protected function getTokenFields($code)
    {
        $fields = [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'code' => $code,
            'redirect_uri' => $this->redirectUrl,
        ];

        if ($this->usesPKCE()) {
            $fields['code_verifier'] = $this->request->session()->pull('code_verifier');
        }

        return $fields;
    }
```

**Comment by taylorotwell** [comment]
I don't have a huge problem with this if someone wants to PR it.

**Comment by driesvints** [comment]
@aaronpk feel free to send in a PR 👍

**Comment by aaronpk** [comment]
Will do, thanks! I've got this on my calendar.

**Comment by driesvints** [comment]
I'm going to close this as we're not looking into doing this ourselves immediately but anyone's still free to PR this if they want. Thanks

**Comment by aaronpk** [comment]
I did the actual code change already, but I still need to write some tests before I'm ready to send a PR for it.

**Comment by ElForastero** [comment]
@aaronpk Can you please commit your latest changes, or just submit a PR? I'm looking forward to be able to use PKCE with Socialite package. 😃

**Comment by aaronpk** [comment]
I just submitted a PR for this! I got the tests to (mostly) work! #518
