### ISSUE TITLE
Include `grant_type=authorization_code` in the core OAuth 2 AbstractProvider

### ISSUE THREAD

**Issue by aaronpk** [laravel/socialite#484]
The parameter `grant_type=authorization_code` is a required parameter in OAuth 2 in the POST request to the token endpoint. It's an unfortunate accident that some of the core providers in this repo don't require it. Any conformant OAuth server will require it, as is evidenced by the number of providers that have to add this property by extending the `getTokenFields` method.

This property should be included by default in [`getTokenFields`](https://github.com/laravel/socialite/blob/5.x/src/Two/AbstractProvider.php#L274), and if for some reason the providers that don't need it actually fail when it's provided, it can be removed specifically for them.

Core providers:

* Bitbucket: required
* Facebook: optional
* GitHub: optional
* Gitlab: required
* Google: required
* LinkedIn: required

For the two providers here that don't require it, they ignore the parameter but won't break if it's included. It's safe to always include in the request. If any third party [socialite providers](https://github.com/SocialiteProviders) for some reason fail if it's included, they can remove the parameter by overriding the `getTokenFields` method.

**Comment by driesvints** [comment]
Thanks. Feel free to PR this if you want.
