### ISSUE TITLE
getAvatar() doesn't return the Facebook avatar

### ISSUE THREAD

**Issue by precompiled** [laravel/socialite#487]
- Socialite Version: v5.0.1
- Laravel Version: v8.4.0
- PHP Version: v7.3.11
- Database Driver & Version: MySQL

### Description:
The `getAvatar()` method doesn't return the publicly available profile image URL. It assumes size/type = normal, which is fine, but it lacks the access token, thus returning the default Facebook "no profile image" image.

If one is to retrieve the avatar, one must append `&access_token=XXXXXXXX...` to the `getAvatar()`, which is not at all obvious. Shouldn't the `getAvatar()` return the public image by default, or at least have the boolean parameter to choose this?

### Steps To Reproduce:
Just call the `Socialite::driver('facebook')->user()->getAvatar()` in the `handleProviderCallback`.

**Comment by driesvints** [comment]
It works just fine for me.

**Comment by galkrisztina** [comment]
@precompiled could you resolve it? I'm still facing this issue.

**Comment by driesvints** [comment]
@precompiled @ptlevi @galkrisztina instead of downvoting my reply, please provide more accurate steps to reproduce. I tested with the above and the avatar urls were publicly accessible for me.

**Comment by precompiled** [comment]
@driesvints  Well, there was nothing more I could tell you apart from what I wrote. It just doesn't work and requires an access token, as mentioned. 😄 

**But!** I've just received an email from Facebook that's related to this.

Take a look at this announcement, under the "**Developer Action Required
Changes to tokenless access for User Picture and FB/IG OEmbed endpoints:**" section:
https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8

Also, under the "User Picture" it mentions access tokens will be (are) needed
https://developers.facebook.com/docs/graph-api/changelog/version8.0#users

https://developers.facebook.com/docs/graph-api/reference/user/picture

It seems to me that since it's such a massive system, they already started rolling this out.

**Comment by precompiled** [comment]
> @precompiled could you resolve it? I'm still facing this issue.

As mentioned originally, I've just appended the `access_token` to the query. Like so:
```
$fbUser = Socialite::driver('facebook')->user(); 
$img = $fbUser->avatar_original . "&access_token={$fbUser->token}
```

Hopefully this won't be needed once the fix comes. :)

**Comment by jadamec** [comment]
I must agree with @precompiled . I had a same problem, so I googled and found this solution https://stackoverflow.com/a/63965774/6597737 and just before opening a new issue here.. found this. :) Hopefully this will be fixed soon. Thanks!

**Comment by jadamec** [comment]
In addition, there also could be an option for the `->getAvatar()` method to choose an image size.

**Steps To Reproduce:**

Socialite::driver('facebook')->user()->getAvatar(1920) will create:
https://graph.facebook.com/v3.3/ID/picture?width=SIZE&access_token=TOKEN

**Comment by edgarsn** [comment]
> In addition, there also could be an option for the `->getAvatar()` method to choose an image size, because that tiny image is absolutely useless.
> 
> **Steps To Reproduce:**
> 
> `Socialite::driver('facebook')->user()->getAvatar(1920)` will create:
> https://graph.facebook.com/v3.3/ID/picture?width=SIZE&access_token=TOKEN

Try using `Socialite::driver('facebook')->user()->avatar_original`. At least then you can crop to your preferred size.

**Comment by jadamec** [comment]
> Try using `Socialite::driver('facebook')->user()->avatar_original`. At least then you can crop to your preferred size.

I know this attribute, however, I often need a different size (e.g. 300px or 980px) and croping it even it already exists.. is quite strange, but thanks... 👍

**Comment by precompiled** [comment]
@edgarsn @driesvints Any chance of actually supporting the variable size, as @jadamec proposed?
How would that work taking other Social providers in account?

Thanks.

**Comment by driesvints** [comment]
I have no idea how this would work with the other providers so I don't believe this can be done here. Socialite is really about authentication. If you need a specific picture format I'd suggest you solve that in user land.

**Comment by driesvints** [comment]
@precompiled thanks for that post btw. Would have helped if you posted that in the original issue. I didn't know they were getting deprecated.

**Comment by precompiled** [comment]
Np. I didn’t have that info at the time, as mentioned in my previous
message. :)

**Comment by driesvints** [comment]
Unfortunately we were forced the fix for this. Please see https://github.com/laravel/socialite/pull/504

**Comment by driesvints** [comment]
Just for reference, there's no good reason really why the current way shouldn't work anymore in v3.3. If anyone's up to file a bug report with Facebook about it they're free too.

**Comment by braymarco** [comment]
we can use this code to get the redirect url provided by getUrl with token

                $url = $user->getAvatar() . '&access_token=' . $user->token;
                $ch = curl_init();

                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);

                $res = curl_exec($ch);
                $redirectedUrl = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
