### ISSUE TITLE
Calling user method twice throws InvalidStateException

### ISSUE THREAD

**Issue by rihardssceredins** [laravel/socialite#490]
- Socialite Version: 5.0.3
- Laravel Version: 7.4.10
- PHP Version: 7.4.10

### Description:
Hey,

I wanted to extract some authorization code from the controller where I'm handling the provider callback to a form request so I could just deal with user creation and log in in the controller itself. 🚀

However that resulted in calling the `user` method twice (first in the form request and then in the controller).

```php
class LoginRequest extends FormRequest
{
    public function authorize()
    {
        return with(Socialite::driver('google')->user(), function (Laravel\Socialite\Contracts\User $user = null) {
            return $user && $user->user['hd'] === 'myorg.com';
        });
    }
}
```

From the code in `AbstractProvider` I understand that calling the `user` method  creates a fresh `User` object every time and without using the `stateless` method it pulls the state out of the session and throws `InvalidStateException` if you call it twice. When I edited the code in `AbstractProvider` to keep the state in the session (instead of pulling it) an `ClientException` is thrown. I guess the reason for that is that the user method tries to fetch a new `access_token` with the code it already used.

What about caching the user object in the `user` method in `AbstractProvider` to avoid doing an external request twice? Something like:

```php
public function user()
{
    if ($this->user) {
        return $this->user;
    }

    // ..
    
    $this->user = $this->mapUserToObject($this->getUserByToken(
        $token = Arr::get($response, 'access_token')
    ));

    return $this->user->setToken($token)
                ->setRefreshToken(Arr::get($response, 'refresh_token'))
                ->setExpiresIn(Arr::get($response, 'expires_in'));
}
```

Or caching the last token data?

```php
public function user()
{
    if ($this->hasInvalidState()) {
        throw new InvalidStateException;
    }

    if (!$this->accessToken) {
        $response = $this->getAccessTokenResponse($this->getCode());
        $this->accessToken = Arr::get($response, 'access_token');
        $this->refreshToken = Arr::get($response, 'refresh_token');
        $this->tokenExpiresIn = Arr::get($response, 'expires_in');
    }

    $this->user = $this->mapUserToObject($this->getUserByToken($this->accessToken));

    return $this->user->setToken($this->accessToken)
                ->setRefreshToken($this->refreshToken)
                ->setExpiresIn($this->tokenExpiresIn);
}
```

This however would require to use the `stateless` method when accessing the `user` method for the second time or changing the `session()->pull('state')` to `session()->get('state')` in `hasInvalidState` method.

What are your thoughts?

### Steps To Reproduce:
Call the `user` method twice within a request when using `google` driver.

```php
class LoginController
{
    public function __invoke()
    {
        Socialite::driver('google')->user();
        Socialite::driver('google')->user();
    }
}
```

**Comment by driesvints** [comment]
You indeed can't call this twice. Caching the user might not be a bad idea. Feel free to send in a PR if you want.
