### ISSUE TITLE
Undefined method scopes when chained

### ISSUE THREAD

**Issue by danilopolani** [laravel/socialite#493]
- Socialite Version: 5.0.3
- Laravel Version: 8.12.3
- PHP Version: 7.4.10
- Database Driver & Version: N/A

### Description:
When chaining `Socialite::driver()` with `scopes()` intellisense returns an error because `scopes()` method is not actually provided within `\Laravel\Socialite\Contracts\Provider`.

TBH I don't know how this could be solved since `Contracts\Provider` is used also in `One` providers that don't have `scopes()` method.
Currently I'm creating a variable assigned to `\Laravel\Socialite\Two\AbstractProvider` with the PHPDoc but I'm pretty sure PHPStan would complain about it because the return type of `driver()` would mismatch to PHPDoc.

### Steps To Reproduce:

```php
<?php

use Laravel\Socialite\Facades\Socialite;

Socialite::driver('github')
  ->scopes([]); // Undefined method 'scopes'.intelephense(1013)
```

**Comment by driesvints** [comment]
We have no plans on digging into this ourselves. Feel free to PR something if you like 👍
