### ISSUE TITLE
Unable to install in composer2

### ISSUE THREAD

**Issue by nomura-kainos** [laravel/socialite#496]
- Composer Version 2
- Socialite Version: 5.1
- Laravel Version: 6.2
- PHP Version: 7.4
- Database Driver & Version:

### Description:

Hello.
When I try to install laravel/socialite with composer2, I can't find the package and it won't install
I tried it with composer1 and it installed with no problems. Could you please check it out?

### Steps To Reproduce:

```
composer require laravel/social  
```

Could not find package laravel/socialite

**Comment by driesvints** [comment]
Works fine for me.
