### ISSUE TITLE
impelement ZarinPal payment system as new provider 

### ISSUE THREAD

**Issue by pooryasadidi6868** [laravel/socialite#497]
**ZarinPal** is an online payment gateway which is the first system started service providing in Iran. They are the only company which have certification of work from central bank of Iran and none of their competitors have this type of certifications.

On the other hand and services side they have the largest bundle of services from interconnection of banks till new channels payment like USSD. On the security area, ZarinPal is the only company which is PCI-DSS and also none of their competitors doesn’t have a trusted SSL which is a basic must on financial areas.

**Comment by driesvints** [comment]
Hey there, please see our readme:

<img width="374" alt="Screenshot 2020-11-17 at 10 51 18" src="https://user-images.githubusercontent.com/594614/99374425-da875200-28c2-11eb-9a0c-3acd27c49dfb.png">
