### ISSUE TITLE
Invalid verification code format when login through facebook app's browser

### ISSUE THREAD

**Issue by shahrizal96** [laravel/socialite#501]
- Socialite Version: ^4.4
- Laravel Version: ^7.0
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:
First of all thanks for the awesome package.
  
I currently develop web app using vue+nuxt (frontend) and laravel(backend). Currently having problem with laravel socialite when browse using mobile facebook application's browser for both ios and android. Its working fine when using web browser such as chrome and etc.

When I click the button (login with facebook) it direct to api that handle callback. However its stuck at that page (blank white page). Then I check sentry and got error "Invalid verification code format" then when refresh got error "This authorization code has been used" where I know where it come from for first error I have no idea.

Here I attach image for the error, code for handle provider, laravel view callback and vue handle login button.

**ErrorInvalid verification code format**
![image](https://user-images.githubusercontent.com/52898588/99937040-9eab2b80-2d9f-11eb-9c83-439d35323454.png)

**Code for handle provider**
![image](https://user-images.githubusercontent.com/52898588/99937084-c4d0cb80-2d9f-11eb-85b1-ae6022fdfd9d.png)

**Laravel view**
![image](https://user-images.githubusercontent.com/52898588/99937101-d1edba80-2d9f-11eb-90f8-4ffeb461fe48.png)

**Vue**
![image](https://user-images.githubusercontent.com/52898588/99937134-e467f400-2d9f-11eb-8ca3-e7a34b218169.png)

![image](https://user-images.githubusercontent.com/52898588/99937149-ed58c580-2d9f-11eb-90a9-ad6e4ebd14dd.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by shahrizal96** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.
> 
> Thanks!

Hi.. After I update the latest version, its still same. Really hope if you can assist me. Thanks in advance.

**Comment by driesvints** [comment]
@shahrizal96 can you maybe try out a support channel first? I very recently tried out the Facebook driver and it worked for me.

**Comment by shahrizal96** [comment]
> @shahrizal96 can you maybe try out a support channel first? I very recently tried out the Facebook driver and it worked for me.

Thanks for the fast response. Really appreciate it.
What do you mean by try out support channel? Kind of new to this community. 
Did you try it through facebook app's browser?
If its possible, do you mind share your blade callback?

**Comment by driesvints** [comment]
One of these:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
