### ISSUE TITLE
getTokenUrl -> $this.config variable empty

### ISSUE THREAD

**Issue by roozeec** [laravel/socialite#503]
- Socialite Version: 5.1.1
- Laravel Version: 8.16.1
- PHP Version: 7.4.13

I'm trying to use Microsoft graph provider (https://github.com/SocialiteProviders/Microsoft-Graph) in order to use for multi tenant app.

The facts : when I use the provider with the .env where I set the Client secret and id, all is working well.
Now I want to setup this configuration on the fly, so I use the setConfig from socialite :

$mycfg = new \SocialiteProviders\Manager\Config($clientId, $clientSecret, $redirectUrl,$additionalProviderConfig);
then I do : 
return Socialite::driver('graph')->setConfig($mycfg)->redirect();

It works for the first step 'authorize' (getAuthUrl)  , but for the second step 'get token' (getTokenUrl) , I got this error : 

Client error: `POST https://login.microsoftonline.com/common/oauth2/v2.0/token` resulted in a `400 Bad Request` response: {"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'cl (truncated...)

Looking at the code, it appears that in function getTokenUrl , the $this->config array is empty, so client_id is missing, I suppose this is the message returned by microsoft.
Looking at the getAuthUrl function, the $this->config array is correct.

When I use the .env file configuration , for the getTokenUrl the config variable is well filled.
But when no data in .env file and set with setConfig , the config variable is empty

Can you help ?

**Comment by driesvints** [comment]
Hi there, 

We don't support this adapter ourselves. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by roozeec** [comment]
Not really sure it is on driver , this problem seems occur a few times https://github.com/laravel/socialite/issues/419

**Comment by roozeec** [comment]
In the microsoft graph provider , i added this function which get the session data ::


    public function getAccessTokenResponse($code)
    {
        if (session('clientId')) {
            $this->clientId = session('clientId');
            $this->clientSecret = session('clientSecret');
            $this->redirectUrl = session('redirectUrl');
        }
        $response = $this->getHttpClient()->post($this->getTokenUrl(), [
            'headers' => ['Accept' => 'application/json'],
            'form_params' => $this->getTokenFields($code),
        ]);
        return json_decode($response->getBody(), true);
    }

And before calling : 


session(['clientId' => $clientId,'clientSecret'=>$clientSecret,'redirectUrl'=>$redirectUrl]);
$additionalProviderConfig = ['tenant_id' => $credential['tenant']];
$mycfg = new \SocialiteProviders\Manager\Config($clientId, $clientSecret, $redirectUrl,$additionalProviderConfig);
return Socialite::driver($auth_mode)->setTenantId($credential['tenant'])->setConfig($mycfg)->redirect();

Not sure , it is the best solution, but it works ...
