### ISSUE TITLE
Cannot login using Twitter due to exception

### ISSUE THREAD

**Issue by smares** [laravel/socialite#505]
- Socialite Version: 5.1.2
- Laravel Version: 8.18.1
- PHP Version: 8.0.0

### Description:
Invoking `Socialite::driver('twitter')->redirect();` throws an exception:

`League\OAuth1\Client\Signature\HmacSha1Signature::League\OAuth1\Client\Signature\{closure}(): Argument #2 ($value) must be passed by reference, value given`

### Steps To Reproduce:
- Configure Twitter API key and secret as required
- Call `Socialite::driver('twitter')->redirect();`

Before I am redirected to Twitter, I get the exception above.

The same call with the `facebook` driver works as expected.

**Comment by smares** [comment]
Seems to be a PHP 8 issue with the dependency, see https://github.com/thephpleague/oauth1-client/issues/127

**Comment by jringeisen** [comment]
@smares I was able to resolve this by removing the & symbol in front of the $key and $value:
```
// replace this
array_walk_recursive($data, function (&$key, &$value) {
    $key = rawurlencode(rawurldecode($key));
    $value = rawurlencode(rawurldecode($value));
});
```
```
// with this
array_walk_recursive($data, function ($key, $value) {
    $key = rawurlencode(rawurldecode($key));
    $value = rawurlencode(rawurldecode($value));
});
```

**Comment by smares** [comment]
With that fix you can just as well remove the lines entirely. ;)

My pull request was already merged in the library, just waiting for a release.
