### ISSUE TITLE
Received HTTP status code [401] with message "{"errors":[{"code":32,"message":"Could not authenticate you."}]}" when getting temporary credentials.

### ISSUE THREAD

**Issue by jringeisen** [laravel/socialite#506]
- Socialite Version: 5.1
- Laravel Version: 8.12
- PHP Version: 8.0
- Database Driver & Version:

### Description:
After integrating Laravel Socialite and the Twitter provider I was receiving the following error:

Received HTTP status code [401] with message "{"errors":[{"code":32,"message":"Could not authenticate you."}]}" when getting temporary credentials.

After spending about 4 hours trying to debug what the issue was I tried leaving the TWITTER_REDIRECT_URI blank and the problem went away.

### Steps To Reproduce:
Integrate Laravel Socialite and the Twitter provider, then add the following to config/services.php:

```
'twitter' => [    
  'client_id' => env('TWITTER_CLIENT_ID'),  
  'client_secret' => env('TWITTER_CLIENT_SECRET'),  
  'redirect' => env('TWITTER_REDIRECT_URI') 
],
```
Now add your Twitter environment variables. If you include the TWITTER_REDIRECT_URI it will throw the error if you leave it blank the error goes away.

**Comment by smares** [comment]
Out of curiosity, what did you enter for `redirect` and what happens after the OAuth flow without the `redirect` set?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jringeisen** [comment]
@smares im developing locally and entered https://plan-and-post.test as the redirect. When I left it blank everything worked as expected and I was redirected to the redirect that I set in my developer portal on Twitter which was the same url as above.

**Comment by jringeisen** [comment]
@driesvints I've posted on discord, StackOverflow, and Laracasts without any luck so far. It's failing in the server.php inside the ```getTemporaryCredentials()``` anytime I include a URL for the redirect. It doesn't matter what the URL is, I've tried a bunch of different ones, it always fails.
```
$response = $client->post($uri, [
   'headers' => $headers,
]);
```
So I inspected the header and the oauth_callback is ```oauth_callback="https%3A%2F%2Fplanandpost.test%2Fsocial-packs``` which matches the URL in my Twitter Developer console.

If I leave the oauth_callback blank I get a 200 response with the oauth_token, oauth_token_secret, and oauth_callback_confirmed=true.

As long as I leave the redirect URL empty, everything works as expected. But I'm trying to save someone from the same headache that I went through.

**Comment by smares** [comment]
Interesting, a project that also deals with Twitter and OAuth has this in the source code: https://github.com/abraham/twitteroauth/blob/d2fdb233ddd35be449ab62b13ff412aca61511e2/src/TwitterOAuth.php#L537

**Comment by jringeisen** [comment]
@smares they’re removing the oauth_callback, hmm..According to the Twitter documentation the oauth_callback is a required field.

**Comment by jringeisen** [comment]
I commented out the oauth_callback in order to remove it from the header to see what would happen and everything worked as expected so I guess I'm confused as to why we even include the oauth_callback in the first place. 

```
protected function temporaryCredentialsProtocolHeader($uri)
    {
        $parameters = array_merge($this->baseProtocolParameters(), [
            // 'oauth_callback' => $this->clientCredentials->getCallbackUri(),
        ]);

        $parameters['oauth_signature'] = $this->signature->sign($uri, $parameters, 'POST');

        return $this->normalizeProtocolParameters($parameters);
    }
```

According to the Twitter documentation, the oauth_callback is a required parameter so I thought it would break and throw an error, but this wasn't the case.

**Comment by smares** [comment]
The Twitter documentation is a mess, I am struggling with media uploads where they write data must be sent as `multipart/form-data` only to later mention that `application/x-www-form-urlencoded` is also OK and when I use `multipart/form-data`, even if I calculate the signature using `oauth_*` fields as by the documentation, I get authentication errors. They write base64 encoded media data should be inside a `media_data` field and only raw data should be in `media`, but then I get an error if I use `media_data` and can happily put base64 data in `media`. So unconsistent, but I am getting off-topic.

**Comment by jringeisen** [comment]
I used the previous package you referenced to handle image uploads, which was pretty straightforward.

**Comment by pushparajbhatta** [comment]
I had been getting the same error at the redirection controller while using oauth 1

`Received HTTP status code [401] with message "{"errors":[{"code":32,"message":"Could not authenticate you."}]}" when getting temporary credentials.`

I found out that I had been using oauth 2 client id and client secret on my configuration. Please make sure you are using the credentials (API Key and Secret) from "Consumer Keys" on twitter app settings. The **API Key** and **Secret** under **"Consumer Keys"** are client id and client secret respectively for oauth 1.
