### ISSUE TITLE
Gitlab scopes not working

### ISSUE THREAD

**Issue by jdecool** [laravel/socialite#507]
- Socialite Version: 5.1.2
- Laravel Version: 8.19.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8.0

### Description:

Defining scopes with Gitlab provider not working because of an incorrect URL parameter format.

The Gitlab scope separator should be `+` and not `,` like it is by default.

But there is a second problem. The `+` character is transformed into `%2B` when the URL is created by `http_build_query`.

### Steps To Reproduce:

Specify two scopes in the redirect action:

```php
return Socialite::driver('gitlab')
    ->setScopes(['read_user', 'read_api'])
    ->redirect();
```

Result this error:

![image](https://user-images.githubusercontent.com/433926/103045197-d4e8f000-4583-11eb-9357-170bc2e6694d.png)

Because of this parameter `&scope=read_user%2Bread_api` in the URL.
Should be `&scope=read_user+read_api`.

**Comment by driesvints** [comment]
This has always worked until now. Did anything changed on GitLab's part?

**Comment by jdecool** [comment]
> This has always worked until now. Did anything changed on GitLab's part?

¯\_(ツ)_/¯

Last night, I've tried to use `SocialiteProviders` and worked with the library.
But when I look how they do, I don't see differences.

I'm going to test the code I used to create this issue. Maybe, it was a Gitlab bug.
Come back with more info soon.

**Comment by driesvints** [comment]
We don't maintain SocialiteProviders sorry. Feel free to report an issue here anew when you've confirm there's a bug.

**Comment by jdecool** [comment]
> We don't maintain SocialiteProviders sorry

I know it

> Feel free to report an issue here anew when you've confirm there's a bug.

Sure, I'll do if I confirm the bug.
