### ISSUE TITLE
Support for self-hosted Gitlab

### ISSUE THREAD

**Issue by JeroenVanOort** [laravel/socialite#509]
The current Gitlab provider only works with gitlab.com. Gitlab also offers the ability to self-host.

Would you be willing to consider a PR an optional override of `gitlab.com`? I'm willing to work on it.

**Comment by driesvints** [comment]
Hmm yes I think we could. Perhaps add `selfHosted` method on the provider which accepts an url that sets the property? Anyway, feel free to send in a PR.

**Comment by JeroenVanOort** [comment]
@driesvints Could you please tag a new relase?

**Comment by driesvints** [comment]
@JeroenVanOort releases are done on Tuesdays so that's today. I'll get to it somewhere today.

**Comment by driesvints** [comment]
@JeroenVanOort I'm sorry I have to revise that. We're not going to do releases today because Taylor is on holiday. We'll do the releases next week.
