### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by raakkan** [laravel/socialite#513]
- Socialite Version: 5.1
- Laravel Version: 8.12
- PHP Version:8.0
- Database Driver & Version: mysql 8

### Description:
ErrorException: Trying to access array offset on value of type null in file /****/vendor/laravel/socialite/src/SocialiteManager.php on line 125

**Comment by JeroenVanOort** [comment]
You don't give much information to reproduce the problem. However, my first guess is that you didn't include an entry for your service in `config/socialite.php`.

**Comment by raakkan** [comment]
this is my services.php

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'postmark' => [
        'token' => env('POSTMARK_TOKEN'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'google' => [
        'client_id' => env('AUTH_GOOGLE_CLIENT_ID'),
        'client_secret' => env('AUTH_GOOGLE_CLIENT_SECRET'),
        'redirect' => env('AUTH_GOOGLE_CLIENT_REDIRECT'),
    ]

];

and this is env

AUTH_GOOGLE_CLIENT_ID=xxxxxxxxxx
AUTH_GOOGLE_CLIENT_SECRET=xxxxxx
AUTH_GOOGLE_CLIENT_REDIRECT=xxxxxx`

**Comment by JeroenVanOort** [comment]
I don't see anything wrong with that at first glance. 

In order to debug this, you could add a `dump($provider, $config);` in the indicated function and post the (redacted) output.

**Comment by raakkan** [comment]
$provider "Laravel\Socialite\Two\FacebookProvider"
$config null

**Comment by raakkan** [comment]
sorry this is my typo problem.
thank you for your reply.
