### ISSUE TITLE
Missing redirect uri parameter

### ISSUE THREAD

**Issue by pyaeswin** [laravel/socialite#514]
- Socialite Version: 4.3
- Laravel Version: 7.24
- PHP Version: 7.4.11

When I query user details, I got this message - 'missing redirect uri paramter'.

That is my code - 
$user = Socialite::driver($provider)->stateless()->user();

And I am using for laravel vue spa auth api.

Edited:
Currently, I got this missage - 'missing authorization code'.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
