### ISSUE TITLE
Client error - missing required "code" parameter

### ISSUE THREAD

**Issue by lbreza** [laravel/socialite#515]
- Socialite Version: 5.1.3
- Laravel Version: 8.22.1
- PHP Version: 7.4

### Description:

I know there were already some of the issues (#294) related to this but this still haven't been fixed and it's bothering me for some time because I can't make it work.

It may be problem only for the specific cases but in some cases it's not working.\
If I'm wrong please correct me.

Problem is with Google provider because it returns the exception when you want to handle the callback and retrieve user details.

`Socialite::driver('google')->stateless()->user()`

returns

`GuzzleHttp\Exception\ClientException
Client error: POST https://www.googleapis.com/oauth2/v4/token resulted in a 400 Bad Request response: { "error": "invalid_request", "error_description": "Missing required parameter: code" }`

![111](https://user-images.githubusercontent.com/44499223/104647871-c2f5fb00-56b2-11eb-9e6d-d8b8d93d83fd.png)

However it works normally if you test it locally (localhost).

You can make it work on live server (production) only when you remove `'profile'` from `$scopes` at `socialite/src/Two/GoogleProvider.php` but you don't receive user details such as `given_name`, `family_name`, ... which are needed.

### Steps To Reproduce:

1. Make sure you're testing it on live server (production) and not locally (localhost).
2. At `socialite/src/Two/GoogleProvider.php` file set
```php
protected $scopes = [
  'openid',
  'profile',
  'email',
];
```
3. Try to login with Google account.
4. Check if `Socialite::driver('google')->stateless()->user()` works and you get all the user information when you handle the callback.

**Comment by driesvints** [comment]
> However it works normally if you test it locally (localhost).

This just leads me to believe there's something wrong with your setup in production.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by lbreza** [comment]
> 
> 
> > However it works normally if you test it locally (localhost).
> 
> This just leads me to believe there's something wrong with your setup in production.
> 
> Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.
> 
>     * [Laracasts Forums](https://laracasts.com/discuss)
> 
>     * [Laravel.io Forums](https://laravel.io/forum)
> 
>     * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> 
>     * [Discord](https://discordapp.com/invite/KxwQuKb)
> 
>     * [Larachat](https://larachat.co)
> 
>     * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> 
> Thanks!

You were right.

After additional debugging and researching I figured out that it was problem with server ModSecurity.\
It was blocking the Google callback request...

Thank you!

**Comment by Hellmuth99** [comment]
@lbreza Could you solve it in the end? I have the same error

**Comment by khoirulyahya** [comment]
yes sir thanks for your answer @emf-developer .
Before i know that, my code like this.

`$user = Socialite::driver($provider)->stateless()->user();`
`$existingUser = User::where('email', $user->email)->first();`

on my history error happen in method user() after stateless()
like your answer, the problem happen when user cancel sign in to process

so we apply try catch like this
      `try {
            $user = Socialite::driver($provider)->stateless()->user();
        } catch (\Exception $e) {
                return redirect()->to('https://blablabla.id/login');
        }`

and it solved. So, thank you sir

**Comment by rkgarcia** [comment]
> like your answer, the problem happen when user cancel sign in to process

Do you know the rules disabled to solve the issue? @lbreza

**Comment by khoirulyahya** [comment]
> > like your answer, the problem happen when user cancel sign in to process
> 
> Do you know the rules disabled to solve the issue? @lbreza

Sir, if you see my solved. In my code We must to make sure, $user is a contain of Socialite get the value before we use in $existingUser. In this case the cancel action make Socialite Not getting value.
Cmiiw or ask me if my answer still confused. Thanks
