### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by PHPGuus** [laravel/socialite#516]
Hi there,

One of my clients has multiple differently-named and differently-branded front end applications all making the use of the one API written in Laravel.
They would like Social Logins, and so here we are.

One of the major issues that I come across is "What do I call the application at the OAuth Integrator's side?" I can't use X because no user of Y or Z knows about X, so it makes no sense... Neither can call it Y or Z for the same reason.

Within the API, though, I know exactly which front end "tenant" the request is coming in from, and so I could present different social configs (loaded from the DB or some place) depending on the "tenant"...

How can I apply this sort of dynamic configuration, though? Looking at the `AbstractProvider`, the (e.g.) `FacebookProvider` and the `SocialiteManager`, there seems to be no way that I can dynamically feed the `SocialiteManager` different configs based on the "tenant".

Are there any plans / designs / ideas to provide for this type of dynamic config? My client is happy enough for me to contribute to OSS, so if there are plans but no developers, I can be the developer.

Alternatively, would you recommend setting up a different config provider (in the `$app->container`) that does something smart when asked for `services.google` and such?

Thank you and best regards,
Guus

**Comment by driesvints** [comment]
Heya. We don't have any plans for a dynamic config. As for the rest of your questions I'll need to redirect you to a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by PHPGuus** [comment]
Hi Dries,

are you guys willing to entertain the idea of having dynamic config capabilities built in to Socialite?

Best regards,
Guus

**Comment by driesvints** [comment]
Not at the time sorry.

**Comment by PHPGuus** [comment]
OK - Thanks
