### ISSUE TITLE
Apple sign in throws exception

### ISSUE THREAD

**Issue by uchamb** [laravel/socialite#521]
- Socialite Version: 5.2
- Laravel Version: 8.0
- PHP Version:7.4.15
- Database Driver & Version: Mysql / 10.3.27-MariaDB

### Description:
userFromToken method throws exception when using apple driver:
**"Not providing the current time is deprecated. Please pass an instance of DateTimeInterface."**

### Steps To Reproduce:
Just try the apple sign in from an iPhone:
$socialUser = Socialite::driver('apple')->userFromToken($token);

I found exactly the same error related to the Laravel passport but I don't have an idea how is it related to this package

Thank you

**Comment by driesvints** [comment]
This package doesn't supports an apple driver. Most likely you're experiencing this issue due to a third party package.

**Comment by engmsaleh** [comment]
@uchamb Any update on this issue, I'm using the `socialite` with the `Apple` provider and got the same issue?

**Comment by uchamb** [comment]
> @uchamb Any update on this issue, I'm using the `socialite` with the `Apple` provider and got the same issue?

I'm using "socialiteproviders/apple" package. The issue was their. As I remember I just updated to the latest 5.0.1 version and it worked.

**Comment by sandeepthakkar23** [comment]
Hello @uchamb 
I have installed  latest version 5.4 even getting same issue.

Please help me
