### ISSUE TITLE
Since last update GoogleProvider class can't be use with api routes

### ISSUE THREAD

**Issue by fabien44300** [laravel/socialite#524]
- Socialite Version: 5.2
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Since last update, the GoogleProvider class can't be use with api routes

path : vendor/laravel/socialite/src/Two/GoogleProvider.php

Now the GoogleProvider class contain a usePCKE = true and in the redirect function, it save a session :
 if ($this->usesPKCE()) {
            $this->request->session()->put('code_verifier', $codeVerifier = $this->getCodeVerifier());
        }
If someone use a api, there is a error message : 

RuntimeException
Session store not set on request.

My temporary solution was to set  usePCKE = false in GoogleProvider.php

### Steps To Reproduce: 
from a api route :
Socialite::driver('google')->stateless()->redirect()->getTargetUrl();

from a web route : it's ok.

**Comment by driesvints** [comment]
This is a duplicate of https://github.com/laravel/socialite/issues/522

Please respond to the questions asked here so we can figure out why this is broken for you: https://github.com/laravel/socialite/issues/522#issuecomment-781361745

**Comment by aaronpk** [comment]
@fabien44300 can you clarify the following:

* what is the redirect URL you're using? Is it a URL on the Laravel API, or is it something on the frontend part of the app?
* are you passing in a state parameter into the redirect method and checking the state on the redirect yourself? If not, this is a security issue
