### ISSUE TITLE
Single Login via Laravel Socialite not working

### ISSUE THREAD

**Issue by the-hardik-sisodia** [laravel/socialite#525]
- Socialite Version: 5.2.0
- Laravel Version: 8.28.1
- PHP Version: 7.3.0
- Database Driver & Version: mysql driver

### Description: 
I have been working on social login recently. My domain needs single login functionality so while creating it, I found that Single Login works perfectly when we use email id/mobile and password to login but when we use socialite and try to login with google, Facebook, or any other provider this doesn't work. We still have sessions active on more than 1 screen/tab if tried to login via social accounts. The functionality for this feature uses laravel's logoutOtherDevices() functionality. Not sure how to handle it with social.

### Steps To Reproduce:
We might need to call a function inside logoutOtherDevices() by which we can log out other devices even when using socialite service. The logoutOtherDevices($request->password) uses $request->password and for the socialite, we don't need one so I think we need to either make an entirely new function for such functionalities

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&amp;channels=%23laravel&amp;prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
