### ISSUE TITLE
Facebook Avatar Picture

### ISSUE THREAD

**Issue by mihai-craita** [laravel/socialite#530]
- Socialite Version: 5.2.0
- Laravel Version: 8.29.0
- PHP Version: 8.0.2
- Database Driver & Version: MySQL

### Description:
Calling getAvatar after retrieving a facebook user, returns a gray, default user picture.
Facebook announced that a token will be required for accessing users pictures. Here is a link with more details: https://developers.facebook.com/docs/graph-api/reference/user/picture#requirements-change

### Steps To Reproduce:
Below is some code reproducing this:

```php

use File;
/* controller code*/
function saveUserPicture() 
{
            $facebookUser = Socialite::driver($this->provider)
                ->fields(
                    [
                        'name',
                        'first_name',
                        'last_name',
                        'email',
                    ]
                )
                ->with(['redirect_uri' => 'my-route'])
                ->stateless()->user();
                
            $fileContents = file_get_contents($facebookUser->getAvatar());
            File::put(public_path() . '/profile/' . $facebookUser->getId() . ".jpg", $fileContents);
}
```

### FIX
Add acces token at the end of the url:
https://graph.facebook.com/VERSION/USER_ID/picture?access_token=ACCESS_TOKEN

**Comment by driesvints** [comment]
Please see a lengthy discussion here: https://github.com/laravel/socialite/issues/487

There's no good reason the old way wouldn't work anymore and if it doesn't please file a bug report with Facebook.
