### ISSUE TITLE
ser

### ISSUE THREAD

**Issue by nabeelzqadri** [laravel/socialite#531]
- Socialite Version: 4.3
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:
In Server.php line 10:

  Declaration of SocialiteProviders\Twitter\Server::getAuthorizationUrl($temp
  oraryIdentifier) should be compatible with League\OAuth1\Client\Server\Serv
  er::getAuthorizationUrl($temporaryIdentifier, array $options = Array)

### Steps To Reproduce:

It was working fine i just install twitter package and now i am getting this can someone please help me on this

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by leepownall** [comment]
@nabeelzqadri, if you are still having problems, update to the [4.1.1 release](https://github.com/SocialiteProviders/Twitter/releases/tag/4.1.1) of the provider.
