### ISSUE TITLE
Getting "{"error":{"message":"Unsupported get request.","type":"GraphMethodException" when login in with Facebook through Socialite and iOS

### ISSUE THREAD

**Issue by alexedwalvarado** [laravel/socialite#534]
When i login with facebook from mobile iphone5 iOS apps and it call laravel API to use socialite, I get this error:

GET https://graph.facebook.com/v3.3/me?access_token=Access_token_here=name,email,gender,verified,link&appsecret_proof=secret_proof_here` resulted in a 400 Bad Request response:

{"error":{"message":"Unsupported get request.","type":"GraphMethodException","code":100,"fbtrace_id":"fbtrace_id_code (truncated...)

I also tried to send this request from Browser or Postman and it works returning Json with user detail as following:

{ "name": "My Facebook Name", "email": "email@mail.com", "id": "personal_facebook_id" }

I also tried to login with another device iOS (Iphone 6) and it works.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
