### ISSUE TITLE
Add extras feature when implementing facebook whatsapp

### ISSUE THREAD

**Issue by jearsonbgomez** [laravel/socialite#535]
Is there a way to implement facebook login using javascript in laravel socialite? Below is the example code from facebook.
  ```
FB.login(function (response) {
  			if (response.authResponse) {
    		const accessToken = response.authResponse.accessToken;
   			fetchSharedWhatsAppAccountIds(accessToken);
  		} else {
    		console.log('User cancelled login or did not fully authorize.');
  		}
	}, {
  		scope: 'business_management,whatsapp_business_management',
  		extras: {
    		feature: 'whatsapp_embedded_signup',
    		setup: {
      ... // Prefilled data can go here
    }
  }
});
```
Can we implement the code below?
```
return Socialite::driver('facebook')
            ->scopes(['whatsapp_business_management', 'business_management'])
            ->extras(['feature' => 'whatsapp_embedded_signup'])
            ->redirect();
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jearsonbgomez** [comment]
@driesvints Thanks for your response. But can you suggest how to implement this feature then?
