### ISSUE TITLE
Allow returning auth url for stateless SPA

### ISSUE THREAD

**Issue by eduardoarandah** [laravel/socialite#536]
I'm trying to handle social logins from a SPA frontend.

My plan is fetching auth url from frontend so redirect and callback can be handled from there.

However, `getAuthUlrl` is marked as protected. 

Is there another way of doing this?
(I don't want to redirect to backend URL so users get redirected again to google)

```
    public function redirect($provider)
    {
        return Socialite::driver($provider)->stateless()->getAuthUrl();
    }

```

**Comment by driesvints** [comment]
It should already be possible to implement Socialite in an SPA. You might want to have a look at https://github.com/joelbutcher/socialstream for inspiration. It implements Socialite in Jetstream for both Livewire and Inertia.

**Comment by eduardoarandah** [comment]
Thanks for the tip. 

However, they’re also using redirect from backend, this is possible because it’s a monolith I guess. 

Socialite api doesn’t have a way of getting redirect URL, should I make a PR ?

returning a redirect
https://github.com/joelbutcher/socialstream/blob/e2828d30d59bacc877639e157ebb6b7dafcc7285/src/Http/Controllers/OAuthController.php#L90

which is a HttpFoundation\RedirectResponse


https://github.com/joelbutcher/socialstream/blob/e2828d30d59bacc877639e157ebb6b7dafcc7285/src/Contracts/GeneratesProviderRedirect.php#L12

**Comment by driesvints** [comment]
Hmm I'm wondering if you need that if Socialite is the right library for you? Thinking it might be better for you to use a library in the ecosystem you use?

**Comment by eduardoarandah** [comment]
I just want to redirect from the SPA frontend without having to redirect to api.mysite.com first. 
Just need to know the url. 

Am I doing something weird? How would you do it (without inertia, just a regular vue app)

**Comment by eduardoarandah** [comment]
Example code for providing frontend with auth url

```
    public function getRedirectUrl($provider)
    {
        // check if provider exists
        if (!config("services.$provider.client_secret")) {
            return abort(404);
        }
        return Socialite::driver($provider)
            ->stateless()
            ->getAuthUrl(null);
    }

```
