### ISSUE TITLE
Google driver InvalidStateException

### ISSUE THREAD

**Issue by komarove** [laravel/socialite#541]
- Socialite Version: 5.2.2
- Laravel Version: 7.30.4
- PHP Version: 7.3.27
- Database Driver & Version: mysql 5.6.43

### Description:
`Laravel\Socialite\Two\InvalidStateException in /vendor/laravel/socialite/src/Two/AbstractProvider.php:236`
I tried `dd(request()->all());` in callback and detected that there is an empty array. It turned out that I had restrictions on the maximum length of `$_GET` (255 characters).  
I think it is like here https://github.com/laravel/socialite/issues/389
### Steps To Reproduce:
Make: `return Socialite::driver('google')->redirect();`
in callback try to `dd(request()->all())` and have empty array, but I can see the parameters in the url. Number of characters +-290.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by evilchis94** [comment]
@komarove Did you manage to solve it? I'm having exactly the same issue...

**Comment by matinwd** [comment]
I have the same problem... Any solutions?

**Comment by quangtd92** [comment]
I run `composer dump-autoload` and. It works for me

**Comment by pipat1995** [comment]
So in conclusion, how can this problem be solved?
I'm facing this problem on both google and face book.
I use Laravel 8 , laravel/socialite 5.2
![image](https://user-images.githubusercontent.com/25393048/126662641-55c5a29d-585c-4257-beea-d757ab1a068a.png)


![Screenshot 2021-07-22 at 22-01-42 🧨](https://user-images.githubusercontent.com/25393048/126661792-f7bb5686-fdd7-4946-b3fb-c6d608c121ca.png)

**Comment by evilchis94** [comment]
@pipat1995 Well, in my case the error was because I started the login request using a subdomain (api.localhost) and the callback url was using another subdomain (app.localhost). I solved it by using one subdomain only but also another solution is using the SESSION_DOMAIN variable from .env file

**Comment by joysendeveloper** [comment]
I am facing the same Problem. Does any one find the solution?
![Screenshot_105](https://github.com/laravel/socialite/assets/119527966/e6eca2f1-d9e6-4fcf-bc93-a09fd81699b8)

**Comment by endel** [comment]
Me too, started happening after running a production application from the same directory as my staging application, tried a bunch of things (clearing caches, setting SESSION_DOMAIN, etc)

**Comment by endel** [comment]
Turns out my problem was solved by clearing the browser cookies. Some cookie on my browser/domain was mixing staging/production environments.

**Comment by marcelocuba10** [comment]
Error:
InvalidStateException 
Solucion:
en el archivo \vendor\laravel\socialite\src\Two\GoogleProvider.php
    protected $scopes = [
        'openid',
        //'profile',
        'email',
    ];
ahi me funciona, pero el nombre del usuario no me trae nada, solo el email y la foto de perfil.
