### ISSUE TITLE
Kindly Provide Support Google One Tap Signin

### ISSUE THREAD

**Issue by hexpit** [laravel/socialite#543]
I tried almost everything and came to the conclusion that socialite doesn't support Google One Tap Signin as it doesn;t work the same way as oAuth does. So I needed to implement a different route than socialite to fetch a user from the $token manually, using the google/apiclient package.

To validate an ID token in PHP, use the Google API Client Library for PHP. Install the library (for example, using Composer):

composer require google/apiclient
Then, call the verifyIdToken() function. For example:

require_once 'vendor/autoload.php';

// Get $id_token via HTTPS POST.

$client = new Google_Client(['client_id' => $CLIENT_ID]);  // Specify the CLIENT_ID of the app that accesses the backend
$payload = $client->verifyIdToken($id_token);
if ($payload) {
  $userid = $payload['sub'];
  // If request specified a G Suite domain:
  //$domain = $payload['hd'];
} else {
  // Invalid ID token
}

Using route provided by socialite for google login gives me 503 error. Please integrate this in socialite.

**Comment by driesvints** [comment]
We're not accepting new drivers, sorry. Please see the readme.

**Comment by hossein** [comment]
@driesvints "Google sign-in button" and "Google one-tap" are popular official Google OAuth login helpers:

https://developers.google.com/identity/gsi/web/guides/display-button

Their front-end part is easy to set up in seconds; they require a backend part to validate the google CSRF and JWT token and map the received JWT token into a Socialite `User` object, what Socialite's Google driver is already doing.

imo this should be supported out of the box in the Socialite Google provider. See e.g this library implementing it: https://github.com/serdud/socialite-google-one-tap
