### ISSUE TITLE
socialite error in Laravel 8

### ISSUE THREAD

**Issue by ramkumawathis** [laravel/socialite#562]
$ composer require laravel/socialite
Using version ^5.2 for laravel/socialite
./composer.json has been updated
Running composer update laravel/socialite
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.3 but your php version (8.0.10) does not satisfy that requirement.
  Problem 2
    - infyomlabs/laravel-ui-coreui is locked to version v3.0.0 and an update of this package was not requested.
    - infyomlabs/laravel-ui-coreui v3.0.0 requires php ^7.3 -> your php version (8.0.10) does not satisfy that requirement.
  Problem 3
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.10) does not satisfy that requirement.

**Comment by mitchierichie** [comment]
This isn't related to Socialite, you have other packages that don't meet your PHP version requirements.

e.g. infyomlabs/laravel-ui-coreui requires php ^7.3

**Comment by ramkumawathis** [comment]
Thank you @driesvints.

Yes, This is not socialite issue. Sorry for the inconvenience.
