### ISSUE TITLE
easier pattern to override mapUserToObject() in a provider

### ISSUE THREAD

**Issue by lsmith77** [laravel/socialite#563]
Maybe it is just my lack of experience with DI in Laravel, but wouldn’t it make sense to have a way to register an alternative callback for mapUserToObject() on a per provider basis to allow easy customization?

Or is the expectation to then register a custom provider, while extending an existing provider?

**Comment by driesvints** [comment]
I personally think it's best to do this in userland. Retrieve the user object and map it into any object you desire. Doing this will keep socialite's code base simple and straightforward.

**Comment by lsmith77** [comment]
my issue was that I wanted to map additional/other fields than the provider covered by default.

**Comment by driesvints** [comment]
Can't you extend the `User` class with your own and do exactly what is displayed in the example you've linked to but then with your extending class?

**Comment by lsmith77** [comment]
Ah .. that was the pattern I was searching for 

I need to extend `User::setRaw()`.

Sorry for being so dense :-/

**Comment by driesvints** [comment]
@lsmith77 no worries at all. Glad you found a solution 👍
