### ISSUE TITLE
Twitter OAuth 2.0

### ISSUE THREAD

**Issue by NewBuidler** [laravel/socialite#570]
Hi,

It seems like Twitter is using the OAuth 2.0 now. 
Is there any plan to use it in Socialite, too? 
Thank you.

**Comment by driesvints** [comment]
Yeah it seems we can look into this. I can look into this eventually but of course we'd accept PR's for anyone wanting to help out here.

https://twittercommunity.com/t/announcing-oauth-2-0-general-availability/163555/2
