### ISSUE TITLE
Twitter Received HTTP status code [401] with message "This feature is temporarily unavailable" when getting token credentials.

### ISSUE THREAD

**Issue by PozitivnaMirta** [laravel/socialite#577]
- Socialite Version: 5.5.0
- Laravel Version: 9.0.0.
- PHP Version: 8.0.0
- Database Driver & Version: MySQL, 

### Description:
Whenever I try to login with Twitter I get: Received HTTP status code [401] with message "This feature is temporarily unavailable" when getting token credentials.
I'm using new Twitter developer portal. I took client id and client secret from here:
![Screenshot_1](https://user-images.githubusercontent.com/96825332/153044651-1b5e9025-1187-4217-9150-f7b8aad48405.png)

### Steps To Reproduce:
I followed Laravel tutorial for setting up socialite, everything is good until it hits: /auth/callback/twitter?oauth_token=yyy&oauth_verifier=xxx

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by PozitivnaMirta** [comment]
Just so anyone needs a solution. The problem was that I called ```Socialite::driver($driver)->user();``` twice during current request.
