### ISSUE TITLE
Twitter changed its API to v2 => getUserInfo not working any more

### ISSUE THREAD

**Issue by boldenkintaro** [laravel/socialite#579]
- Socialite Version: 5.5
- Laravel Version: 9.2
- PHP Version: 8.0.2
- Database Driver & Version:

### Description:
When you sign up as a Twitter developer, you now get the so called "Essential access", which only allows to access Twitter API v2 endpoints. Getting the user info via Socialite::driver('twitter')->user() however accesses a Twitter v1.1 endpoint, which throws an exception:

Received error [{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}
] with status code [403] when retrieving token credentials. {"exception":"[object] (Exception(code: 0): Received error [{\"errors\":[{\"message\":\"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve\",\"code\":453}]}
] with status code [403] when retrieving token credentials. at /var/www/html/vendor/league/oauth1-client/src/Server/Server.php:279)

I tried to apply for the Elevated access, which allows access to v.1.1 endpoints, but the application is quite difficult and I find myself emailing back and forth with Twitter, because they want to know in detail how my application access Twitter's data, how the application will look like, what things are automated etc. Having just begun with the application I don't have final designs and what I responded to Twitter seems to not suffice for Elevated access, yet.
 

### Steps To Reproduce:

No public repo, but this is my source code using Socialite:

`<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Laravel\Socialite\Facades\Socialite;

class TwitterController extends Controller
{
    public function login(Request $request)
    {
        return Socialite::driver('twitter')->redirect();
    }

    public function callback(Request $request)
    {
        $twitterUser = Socialite::driver('twitter')->user();

        $user = User::updateOrCreate([
            'twitter_id' => $twitterUser->id,
        ], [
            'name' => $twitterUser->name,
            'email' => $twitterUser->email,
            'twitter_token' => $twitterUser->token,
            'twitter_refresh_token' => $twitterUser->refreshToken,
        ]);

        Auth::login($user);

        return redirect('/dashboard');
    }
}`

**Comment by driesvints** [comment]
I'm guessing you haven't tried the `twitter-oauth-2` driver? 

<img width="793" alt="Screenshot 2022-04-11 at 10 19 18" src="https://user-images.githubusercontent.com/594614/162694744-651d15f6-877c-47dc-8e22-a4a3d92a92e5.png">
