### ISSUE TITLE
twitter-oauth-2 always returns null for email

### ISSUE THREAD

**Issue by Yahav** [laravel/socialite#587]
- Socialite Version: v5.5.2"
- Laravel Version: 8.78.1
- PHP Version: 7.4.24 

### Description:

Simply using the twitter-oauth-2 provider, the returned user will always return null as the email.

EDIT:
It seem that Twitter oauth 2 still doesn't support getting the email of the authenticated user (which is odd enough) and officially suggesting using oauth 1 for such requirement. however, Socialite Twitter oauth 1 doesn't seem to work at all.
I'm getting the following at the redirection controller:
`Received HTTP status code [401] with message "{"errors":[{"code":32,"message":"Could not authenticate you."}]}" when getting temporary credentials.`

**Comment by driesvints** [comment]
It seems the OAuth 2.0 api indeed doesn't allows you to retrieve the email address.

For the OAuth 1.0 issue: there's lots of apps running this driver in production right now. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by pushparajbhatta** [comment]
I had been getting the same error at the redirection controller while using oauth 1

`Received HTTP status code [401] with message "{"errors":[{"code":32,"message":"Could not authenticate you."}]}" when getting temporary credentials.`

I found out that I had been using oauth 2 client id and client secret on my configuration. Please make sure you are using the credentials (API Key and Secret) from "Consumer Keys" on twitter app settings. The API Key and Secret are client id and client secret respectively for oauth 1.
