### ISSUE TITLE
502 Bad Gateway When callback social of facebook by laravel homestead

### ISSUE THREAD

**Issue by asterism612** [laravel/socialite#593]
- Socialite Version: ^5.5
- Laravel Version: 9.17
- PHP Version: 8.1
- Database Driver & Version:

I am using google, facebook login, but 502 bad gateway is displayed in facebook callback only
Can access the callback,
but Error when reading Socialite::driver($social)->user();
502 bad gateway

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
