### ISSUE TITLE
Stateless + PKCE is accessing session

### ISSUE THREAD

**Issue by decaluwepatrick** [laravel/socialite#594]
- Socialite Version: 5.5.2
- Laravel Version: 8.28.1
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Description:

I am using stateless redirect for a few provider without any issues, but for Twitter (which is the only one that requires PKCE) using `stateless()`   with oauth2 is not working, as `AbstractProvider` accesses the session storage anyway:

```
        if ($this->usesPKCE()) {
            $this->request->session()->put('code_verifier', $this->getCodeVerifier());
        }
``` 

My solution was to extend  `TwitterProvider` to no read from the session, but I wonder if I am the only one experiencing this and if there is a better way fix this

### Steps To Reproduce:

add `'oauth' => 2` to twitter in services.php:

    'twitter' => [
        'client_id' => env('TWITTER_API_KEY'),
        'client_secret' => env('TWITTER_API_SECRET_KEY),
        'redirect' => env('APP_URL') . '/twitter/callback',
         'oauth'=>2 // this value
    ]

Call twitter socialite with stateless: 

```
$redirectUrl = Socialite::driver('twitter')
            ->stateless()
            ->scopes($scopes)
            ->with($payload)
            ->redirect()
            ->getTargetUrl();
```

**Comment by decaluwepatrick** [comment]
similar to #527  and #523  but it seems that proposed solutions where to disable PKCE  (which is not supported by Twitter) or not use stateless (which is not an option in my case)

**Comment by driesvints** [comment]
I'll re-open once you can answer my question. Thanks

**Comment by nomut** [comment]
I got this issue too, while making SPA Auth with JWT.

My problem happen when using with Laravel `api.php` route (there is no `\Illuminate\Session\Middleware\StartSession::class` in the route middleware at Laravel `/app/Http/kernel.php`)

That make `$this->request->session()` not usable.
