### ISSUE TITLE
Stateless Facebook: This authorization code has been used.

### ISSUE THREAD

**Issue by vgavrilovikj** [laravel/socialite#600]
- Socialite Version: ^5.5
- Laravel Version: 8.65
- PHP Version: 8.2.3
- Database Driver & Version: MariaDB 10.6

### Description:
I have implemented the laravel socialite stateless, because I am using Laravel as a backend app with REST APIs and my frontend is in Angular. I get the correct redirect URL, however when I enter my Facebook credentials and agree to proceed with the application I get redirectet to my site with the following issue:
<pre>Client error: `POST https://graph.facebook.com/v3.3/oauth/access_token` resulted in a `400 Bad Request` response: {"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"error_subcode":36009,"f (truncated...)</pre>

Here's the routes in **api.php**
<pre>
Route::get('/auth/redirect/{provider}', [AuthController::class, 'redirectToProvider'])
    ->where('provider', '[A-Za-z]+');
Route::get('/auth/{provider}/callback', [AuthController::class, 'handleProviderCallback'])
    ->where('provider', '[A-Za-z]+');
</pre>

And the following functions in my controller **AuthController.php**
<pre>
/**
     * @param $provider
     * @return JsonResponse
     */
    public function redirectToProvider($provider): JsonResponse
    {
        $response = $this->authService->redirectToProvider($provider);
        return response()->json($response);
    }

    /**
     * @param $provider
     * @param Request $request
     * @return JsonResponse
     * @throws \App\Exceptions\Custom\CustomValidationException
     */
    public function handleProviderCallback($provider, Request $request): JsonResponse
    {
        ValidationUtils::validate($request->all(), [
            'code' => 'required',
        ]);

        $response = $this->authService->handleProviderCallback($provider);
        return response()->json($response);
    }
</pre>

And this is where it resolves in the **AuthServiceImpl.php**
<pre>
/**
     * @param $provider
     * @return array[]
     */
    public function redirectToProvider($provider): array
    {
        if (!in_array($provider, self::PROVIDERS)) {
            throw new CustomNotFoundException(trans('errors.not_found.provider'));
        }

        $success['provider_redirect'] = Socialite::driver($provider)->stateless()->redirect()->getTargetUrl();

        return [
            'data' => $success
        ];
    }

    /**
     * @param $provider
     * @return array[]|void
     */
    public function handleProviderCallback($provider)
    {
        if (!in_array($provider, self::PROVIDERS)) {
            throw new CustomNotFoundException(trans('errors.not_found.provider'));
        }

        try {
            $providerUser = Socialite::driver($provider)->stateless()->user();

            if ($providerUser) {
                $user = $this->socialAccountsService->findOrCreate($providerUser, $provider);
                $user->markEmailAsVerified();
                $token = $user->createToken(env('API_AUTH_TOKEN_PASSPORT_SOCIAL'))->accessToken;

                return [
                    'data' => [
                        'tokens' => [
                            'token_type' => 'Bearer',
                            'expires_in' => 5400,
                            'access_token' => $token
                        ],
                        'user' => new UserResource($user)
                    ],
                    'message' => trans('auth.login')
                ];
            }
        } catch (\Exception $e) {
            throw new CustomUnauthorizedException($e->getMessage());
        }
    }
</pre>

### Steps To Reproduce:
You can try it yourself by logging in with Facebook on the following link: https://afillix.common.mk/login
![image](https://user-images.githubusercontent.com/29601489/183501164-d9be57f6-c658-4c76-9b5e-91a6f963a788.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by vgavrilovikj** [comment]
@driesvints please do not close it as it is not completed and I am still searching for help 🤌  I have already tried StackOverflow.

So please let it open until it's really solved, or would be good to hear your help😄

**Comment by driesvints** [comment]
Please link to the stackoverflow thread. Please try the forums as well as well as discord

**Comment by vgavrilovikj** [comment]
Stackoverflow: https://stackoverflow.com/questions/73283467/laravel-socialite-this-authorization-code-has-been-used-facebook

Yup already added to other forums too.

**Comment by vgavrilovikj** [comment]
@driesvints I've posted on all the channels and have not found a solution. Could you please help?

**Comment by driesvints** [comment]
This doesn't seems like a Socialite issue. Please try a support channel as I can't provide support myself here.

**Comment by vgavrilovikj** [comment]
What do you think it's an issue with? Because I am getting the error from Facebook so I believe it is related to Socialite?

**Comment by vgavrilovikj** [comment]
I am sorry but it appears to be an issue with Socialite unfortunately.

This is the one line of code that I have in the try catch block
![image](https://user-images.githubusercontent.com/29601489/184327374-e08e2c61-a64f-44ee-aba0-c88375f5ebbc.png)

and I am getting the following error:
![image](https://user-images.githubusercontent.com/29601489/184327477-d744ed5c-6777-486f-a803-e6a3e0dc4e66.png)

So it's clear that the issue comes from that line of code.

**Comment by driesvints** [comment]
If you really believe this is an issue then feel free to send in a PR that's non-breaking.

**Comment by vgavrilovikj** [comment]
If I knew the fix I would have haha. The thing is that I am not sure what is causing the issue hence why I opened one and I am asking for your help! @driesvints
