### ISSUE TITLE
Facebook Avatar

### ISSUE THREAD

**Issue by Hillcow** [laravel/socialite#601]
Using the "facebook" driver, the following will always get the [default facebook profile picture](https://i.stack.imgur.com/lABiT.jpg):

```
$user = Socialite::driver("facebook")->user();
$avatar = $user->getAvatar();
```

I use this workaround, which should be a very easy fix to implement:

```
$access_token = $user->token;
$avatar .= "&access_token={$access_token}";
```

This issue has been around for [more than 2 years](https://stackoverflow.com/questions/63935897/laravel-socialite-always-grab-default-avatar), by the way.

**Comment by driesvints** [comment]
We'd welcome a PR that's non-breaking 👍
