### ISSUE TITLE
Google driver / API SDK version used

### ISSUE THREAD

**Issue by chammeow** [laravel/socialite#602]
Hi may we know what version of the Google driver / API SDK used in socialite? Currently we're having issues on invalid token. We're investigating if problem is about versions used. Thanks!

**Comment by driesvints** [comment]
Here's the endpoint: https://github.com/laravel/socialite/blob/5.x/src/Two/GoogleProvider.php#L49

**Comment by chammeow** [comment]
Thank you very much. A great help!
