### ISSUE TITLE
Monday socialite driver is not working

### ISSUE THREAD

**Issue by philippsalesy** [laravel/socialite#605]
- Socialite Version: 5.5.5
- Socialiteproviders/monday: 5.0.0
- Laravel Version: 8.83.16
- PHP Version: 8.1.3
- Database Driver & Version:

### Description:
I am having an issue with the implementation of the [monday](https://socialiteproviders.com/Monday/) socialite driver. I have followed the installation and usage steps as follows below. It throws me the following error when i try to access http://localhost/auth/monday - the exact stack trace can be found [here](https://flareapp.io/share/V7jrZR37#F69) : 
`Call to undefined method SocialiteProviders\Monday\Provider::additionalConfigKeys()
`

EventServiceProviders.php
```
protected $listen = [
        //Socialite OAuth driver
        \SocialiteProviders\Manager\SocialiteWasCalled::class => [
            'SocialiteProviders\SalesForce\SalesForceExtendSocialite@handle',
            'SocialiteProviders\Monday\MondayExtendSocialite@handle',        

        ],
    ];

```

config/app.php

```
Route::get('/auth/monday', [AuthenticatedSessionController::class, 'redirectToMonday']);
Route::get('/auth/monday/callback', [AuthenticatedSessionController::class, 'handleMondayCallback']);
```

config/services.php
```
'monday' => [    
        'client_id' => env('MONDAY_CLIENT_ID'),  
        'client_secret' => env('MONDAY_CLIENT_SECRET'),  
        'redirect' => env('MONDAY_REDIRECT_URI') 
      ],
```

AuthenticatedSessionController.php
```
public function redirectToMonday ()
    {
        return Socialite::driver('monday')->redirect();
    }

    public function handleMondayCallback () 
{
            return redirect('/dashboard');
}
```

**Comment by driesvints** [comment]
We don't maintain this so please ask on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
