### ISSUE TITLE
breaking change in v5.5.6

### ISSUE THREAD

**Issue by mnaas** [laravel/socialite#608]
- Socialite Version: 5.5.6
- Laravel Version: 8.83.26
- PHP Version: 8.1.1
- Database Driver & Version: postgres

### Description:
For v5.5.2 and th versions before user attributes used to be listed in the root. After upgrading to v5.5.6 user attributes are  moved to be inside an "attribute" attribute. Is not this considered a breaking change to be done in non major version?

### Link to the commit and changes done
https://github.com/laravel/socialite/pull/607/commits/8225dcb19a14f5b38b2538d46cec1d1e00c458df#diff-c590ae9e08c25c73ff9f4aff0291e5a986615c1110d5f6aa3d4110da99b0adfcR142

**Comment by driesvints** [comment]
@mnaas I don't think this is breaking? The previous behavior still works. Just an extra attributes property was added. Any other properties are still populated. What broke for you?

**Comment by AmrSoliman** [comment]
The main problem is that when updating composer, expect updates with minor and patch versions will not have breaking changes but bug fixes and security issues.

**Comment by driesvints** [comment]
But what's the breaking change? Please give me some code to reproduce anything that's breaking.

**Comment by mnaas** [comment]
@driesvints thanks for your response.

Before the last change in question this was the response content

```
Laravel\Socialite\Two\User {#0000 ▼
  +id: null
  +nickname: null
  +email: null
  +user: []
}
```

After the change:

```
Laravel\Socialite\Two\User {#0000 ▼
  +attributes: [
   'id' => null
   'nickname' => null,
   'email' => null
  ]
  +user: []
}

so in the application we use attributes directly from the root data, we had a problem and took us sometime to figure out that there was a change in the data structure and we had to get it from the `attributes` attribute

**Comment by driesvints** [comment]
How do you get that response? Please give me the code to reproduce this.

**Comment by mnaas** [comment]
We authenticate with a private OAuth2 provider not a public one. Let me see if I can provide more info that can help.

**Comment by mnaas** [comment]
@driesvints 
Sorry my bad. I just wrote a non realistic example. I can see now after reviewing the changed code and the real data in the response that the problem is with the custom attributes returned. So only attributes exists in the AbstractUser.php class are listed in the root data, while all custom are moved to the `attribtue` attribute array. I just updated the data of the responses above.

**Comment by driesvints** [comment]
But again: how is this response formed? What are you doing to get this?

**Comment by mnaas** [comment]
As I mentioned earlier I make a OAuth2 request using a custom provider:

```
$user = \Laravel\Socialite\Facades\Socialite::with('custom_provider')->user();    
```

Which implements the function:

```
protected function mapUserToObject(array $user)
{

    return (new User())->setRaw($user)->map([
        'id'  => $user['id'],
        'first_name' => $user['first_name'],
        'last_name' => $user['last_name'],
        'name' => $user['first_name'] . ' '. $user['last_name'],
        'email' => $user['email'],
        'avatar' => $user['avatar']
    ]);
}
```

**Comment by driesvints** [comment]
This still does not contain the code of how the "response" is created.

**Comment by driesvints** [comment]
Is it the "$user" object you're referring to? If so, how are you inspecting it?

**Comment by driesvints** [comment]
Closing this for now.
