### ISSUE TITLE
Laravel Socialite Cognito is destroying the session on login

### ISSUE THREAD

**Issue by basiltap** [laravel/socialite#609]
- Socialite Version: "socialiteproviders/cognito": "^4.1",
                                  "laravel/socialite": "^5.5",
- Laravel Version: "laravel/framework": "^9.19",
- PHP Version: 8.1.9",
- Database Driver & Version:

"bumbummen99/shoppingcart": "^4.2",

### Description:

Working in Laravel 9 with LaravelShoppingcart (bumbummen99/shoppingcart) and Socialite Cognito. I have a registration schedule where students can apply for diverse courses and added to the Cart. At the checkout I make an authentication with cognito, but it returns a new session and destroy the last session where the cart is stored.

I have checked the docs and the config files, but I cannot find any point about this.

Can you help me, please?

Working in Laravel 9 with LaravelShoppingcart and Socialite Cognito. I have a registration schedule where students can apply for diverse courses and added to the Cart. At the checkout I make an authentication with cognito, but it returns a new session and destroy the last session where the cart is stored.

I have checked the docs and the config files, but I cannot find any point about this.

Can you help me, please?

### Steps To Reproduce:

Add something to cart
Login through cognito to go the checkout page
After return Socialite::driver('cognito')->redirect(), once in handleProviderCallBack(Request $request), there is nothing in the session() neither in Cart::content()
Cart lost!

**Comment by driesvints** [comment]
We don't maintain this package unfortunately. Please open an issue on their issue tracker.
