### ISSUE TITLE
Google auth callback throws exception `invalid_grand`: `Bad Request`

### ISSUE THREAD

**Issue by PostScripton** [laravel/socialite#611]
- Socialite Version: 5.5.6
- Laravel Version: 9.41.0
- PHP Version: 8.1.13

### Description:
In the production, Sentry (error-reporting app) **occasionally** catches exceptions:

**`GuzzleHttp\Exception\ClientException`**
```
Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

### Steps To Reproduce:

I cannot provide you steps to reproduce because there is no way for us to understand why this is rarely happening.

There's the code in our controller:

```php
// LoginController.php

public function socialLoginRedirect(Request $request, string $social): RedirectResponse
{
    return Socialite::driver($social)
        ->stateless()
        ->with([
            'state' => sprintf(
                'oauth_mode_id=%s&oauth_affiliate_code=%s',
                $request->get('model_id'),
                $request->get('affiliate_code'),
            ),
        ])
        ->redirect();
}

public function handleProviderCallback(Request $request, string $social): RedirectResponse
{
    parse_str($request->input('state'), $state);
    
    $userSocial = Socialite::driver($social)->stateless()->user();
    
    // ...
    $modelId = $state['oauth_model_id']
    $affiliateCode = $state['oauth_affiliate_code']
}
```

In case, you are wondering why we are overriding the `state` is because we use a stateless auth and we need to pass some data through google auth. According to [this post](https://vpalos.com/2021/09/10/dynamic-custom-data-via-oauth-with-laravel-socialite/), only the `state` property passes further the google auth, any different disappears.

We couldn't reproduce this issue locally, this happens only in the production and not all the time.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by PostScripton** [comment]
https://github.com/laravel/socialite/issues/389

**Comment by krit0627** [comment]
2024 same issuse too when login with google

**Comment by CharlesLightjarvis** [comment]
2025 same issues

**Comment by vgavrilovikj** [comment]
Has anyone solved this issue..?

**Comment by vgavrilovikj** [comment]
@CharlesLightjarvis @krit0627 ?

**Comment by CharlesLightjarvis** [comment]
@vgavrilovikj yo brother yes for me.... but u have to know.... I use laravel only for API and React for the frontend separately... i found it on google after 5 days searching.. xD... follow the exact steps and it works 100% 

https://igloo.hr/google-login-with-react-and-laravel-api/

**Comment by krit0627** [comment]
> [@CharlesLightjarvis](https://github.com/CharlesLightjarvis) [@krit0627](https://github.com/krit0627) ?

Pls follow this link, and I think should clear all cache after login with google and try again.

https://www.youtube.com/watch?v=p0I25hL3pBI

. . .

Run Command : php artisan serve --host=localhost

Use : http://localhost:8000/ for testing
