### ISSUE TITLE
Deprecation warnings in php 8.1 if config value 'redirect' is not set

### ISSUE THREAD

**Issue by pohjolal** [laravel/socialite#612]
- Socialite Version: v5.5.6
- Laravel Version: 9.45.1
- PHP Version: 8.1.2
- Database Driver & Version: pdo-mysql, 8.0.31

### Description:

Laravel\Socialite\SocialiteManager generates deprecation warnings from formatRedirectUrl-method if config value 'redirect' is not set. If it is not set formatRedirectUrl calls Str::startsWith with null value.

### Steps To Reproduce:

Problem is visible when using socialite provider socialiteproviders/saml2.

**Comment by driesvints** [comment]
Thanks. I fixed the issue in the latest commit. Will come out on next release day.
