### ISSUE TITLE
ERROR: Undefined index: id FacebookProvider.php:120

### ISSUE THREAD

**Issue by edgarl2a** [laravel/socialite#613]
- Socialite Version: 5.5.6
- Laravel Version: 8.83.27
- PHP Version: 7.4.3
- Database Driver & Version: 

### Description:
When I try to get user from token with the following code:

$driver = Socialite::driver($input['provider']);
if ($input['provider'] === 'facebook') {
    $driver = $driver->fields([
        'email'
    ]);
}
$response = $driver->userFromToken($input['provider_token']);

I get this error:

ERROR: Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at vendor/laravel/socialite/src/Two/FacebookProvider.php:120)

### Steps To Reproduce:

I get the token from a test user in my Facebook app.

$driver = Socialite::driver($input['provider']);
if ($input['provider'] === 'facebook') {
    $driver = $driver->fields([
        'email'
    ]);
}
$response = $driver->userFromToken($input['provider_token']);

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
