### ISSUE TITLE
Use Socialite through a proxy

### ISSUE THREAD

**Issue by vardyb** [laravel/socialite#624]
Laravel: v8.83.26
Socialite: v5.5.6
Okta Provider: v1.1.0

Hi I'm using Socialite to authenticate my users through Okta, however I now need to connect to Okta via a web proxy in our environment.  Is there a way using Socialite to configure it to use a proxy when authenticating a user with Okta?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
