### ISSUE TITLE
[REQUEST] JWT Support

### ISSUE THREAD

**Issue by raif-ar** [laravel/socialite#632]
I was using Socialite with Google Sign-in for my Authentication.
Google was giving me OAuth tokens as response. Now, it is deprecating and they are migrating to a newer version which instead returns to me JWT id tokens.

When I did the migration, Socialite was unable to validate it correctly and always threw an error.

Do you guys have any plan to support JWT?

**Comment by driesvints** [comment]
Right now, we have no plans for this ourselves, sorry.
