### ISSUE TITLE
I Con't Add Multi Google Account

### ISSUE THREAD

**Issue by DXSpring** [laravel/socialite#633]
In Services.php I add :

`'sign_in_google' => [
        'client_id' => env('SIGN_IN_GOOGLE_ID'),
        'client_secret' => env('SIGN_IN_GOOGLE_SECRET'),
        'redirect' => 'http://localhost:8000/sign-in/google/callback',
    ]`

`'sign_up_google' => [
        'client_id' => env('SIGN_UP_GOOGLE_ID'),
        'client_secret' => env('SIGN_UP_GOOGLE_SECRET'),
        'redirect' => 'http://localhost:8000/sign-up/google/callback',
    ]`

When I Try To Use It By Controller:

`public function signInRedirect()
    {
        return Socialite::driver('sign_in_google') -> redirect();
    }`

It's Show Error:

`Driver [user_sign_in_google] not supported.`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
