### ISSUE TITLE
New Google sign-in

### ISSUE THREAD

**Issue by mikelina** [laravel/socialite#634]
On March 31, 2023 Google deprecated the JS Library used for sign-in (https://developers.google.com/identity/sign-in/web/sign-in?hl=en)
The new library (https://developers.google.com/identity/gsi/web/guides/overview?hl=en) returns a JWT token instead of an access token.
Will you update socialite in order to handle this new feature?

**Comment by driesvints** [comment]
Heya, yeah I think we should migrate to the new way of doing things. This would have to be a PR sent in to master for the next major version.

The guide here can help: https://developers.google.com/identity/gsi/web/guides/migration?hl=en

We'd appreciate any help with this.

**Comment by nunomaduro** [comment]
@mikelina Are you able to make a pull request fixing the issue you have described, along with corresponding tests?

**Comment by CosminBd** [comment]
@nunomaduro I'm actively working on an implementation for this.

**Comment by nunomaduro** [comment]
@CosminBd Thank you! Let's follow up on the discussion on the pull request itself! ✅

**Comment by driesvints** [comment]
Looks like Taylor wants this to be a community driver, sorry.

**Comment by mikield** [comment]
I do not think that this is an issue for [socialite](https://github.com/laravel/socialite). 
[socialite](https://github.com/laravel/socialite) is handling OAuth flow, but Google new auth system via Google Identify Service uses JWT auth, so there is no place to new google auth system for [socialite](https://github.com/laravel/socialite) package.
