### ISSUE TITLE
Invalid client

### ISSUE THREAD

**Issue by serhatopcu** [laravel/socialite#635]
### Socialite Version

5.6.1

### Laravel Version

10

### PHP Version

7.4

### Database Driver & Version

mysql

### Description

After signing in with Apple, I am getting the following error when I am redirected to the callback page.

GuzzleHttp\Exception\ClientException
Client error: `POST https://appleid.apple.com/auth/token` resulted in a `400 Bad Request` response: {"error":"invalid_client"} 

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by driesvints** [comment]
I don't think we have an Apple driver? Most likely this needs to be reported to the third party library you're using.

**Comment by zackAJ** [comment]
I had the same issue, it turns out I wasn't providing the key_id AKA kid
