### ISSUE TITLE
Linkedin provider: get user data

### ISSUE THREAD

**Issue by Gerbenodk** [laravel/socialite#655]
### Socialite Version

1.6.1

### Laravel Version

10.41.0

### PHP Version

8.1.4

### Description

LinkedIn updated their products and deprecated the product "[Sign In with LinkedIn](https://learn.microsoft.com/nl-nl/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin)" and changed it to ["
Sign In with LinkedIn using OpenID Connect"](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext). When using `Socialite::driver('linkedin')->stateless()->user();` the API endpoint **/me** has not enough permissions, the new endpoint is: **/v2/userinfo** with scope **'openid'.*

### Steps To Reproduce

Install latest version of both this package as Laravel

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by mbh00** [comment]
I ran into this problem also.
i didn't figure out guys already updated the provider. there are two linkedin providers now
I used 'linkedin-openid' instead of 'linkedin'
Socialite::driver('linked-openid')
also make sure to add an entry for linked-openid in the service file config
