### ISSUE TITLE
Linkedin provider: get user data 

### ISSUE THREAD

**Issue by Gerbenodk** [laravel/socialite#656]
### Socialite Version

5.8.1

### Laravel Version

10.41.0

### PHP Version

8.1.4

### Description

Yesterdays [issue](https://github.com/laravel/socialite/issues/655) had the wrong version of socialite.

LinkedIn updated their products and deprecated the product "[Sign In with LinkedIn](https://learn.microsoft.com/nl-nl/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin)" and changed it to ["
Sign In with LinkedIn using OpenID Connect"](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext), as of the 1 aug 2023. When using Socialite::driver('linkedin')->stateless()->user(); the API endpoint **/me** has not enough permissions, the new endpoint is: **/v2/userinfo** with scope **'openid'.**

### Steps To Reproduce

Install latest version of both this package as Laravel

**Comment by sinarahmany** [comment]
That`s right. I`m having the same issue

**Comment by avdheshsolanki** [comment]
Yes was struggling the same issue from last two days, looking for the solution.

**Comment by sajaddp** [comment]
same issue

**Comment by sajaddp** [comment]
I have the same problem.
In my opinion, if the problems of #651 are fixed to pass the tests, it will be faster than creating a new PR.

**Comment by driesvints** [comment]
Hi all. We'd appreciate a PR to master to implement the new LinkedIn way of doing things.

**Comment by driesvints** [comment]
Hi all. There's a PR up now. Can you all help us verify that it works for you? https://github.com/laravel/socialite/pull/660
