### ISSUE TITLE
sending wrong scope for linkedin

### ISSUE THREAD

**Issue by fkhodamoradi** [laravel/socialite#668]
### Socialite Version

5.9.1

### Laravel Version

10.0

### PHP Version

8.2

### Description

for integrate with linkedin, this package send default scopes as : r_liteprofile, r_emailaddres

both of them have been change by linked in, the correct values is : profile, openid and email

### Steps To Reproduce

Route::get('/redirect', function () {
    return Socialite::driver('linkedin')
        ->scopes(['openid', 'profile', 'email'])
        ->redirect();
});

**Comment by RealMrHex** [comment]
same as #649

**Comment by driesvints** [comment]
You'll need to use the open id provider: https://github.com/laravel/socialite/pull/662
