### ISSUE TITLE
Exception on Linkedin: Undefined array key "storageSize"

### ISSUE THREAD

**Issue by alkin** [laravel/socialite#669]
### Socialite Version

5.8.1

### Laravel Version

9.52

### PHP Version

8.2

### Description

A small set of Users are getting an exception when trying to connect with Linkedin. I believe Linkedin is not returning the avatar image as expected by Socialite.

![image](https://github.com/laravel/socialite/assets/131324/ad832c70-1452-4a86-a975-41848e49dad1)

My suggestion is to simply ignore this error using "@" before the expression:

`return @$image['data']...`

### Steps To Reproduce

We couldn't find a way to reproduce the bug. But this affects specific users every time. Probably there is something different with their accounts or avatars, so that linkedin API returns a slightly different data.

**Comment by shahedgain** [comment]
I'm also facing the same issue.

**Comment by driesvints** [comment]
Are you sure you don't need to use the openid linkedin provider instead of the regular one?

**Comment by alkin** [comment]
I guess i could use the OpenID provider but i believe that wouldn't solve the problem for the regular provider.

We have been using the regular LinkedIn provider for years on this specific project without problems. Without any changes to our code, we started experiencing the exception described. This means that Linkedin changed their behavior and how avatar images are saved internally. We should update socialite to consider this change. Otherwise, i believe more and more people will start to experience the issue, as Linkedin moves to this new data structure.

I will test the OpenID provider soon and post here the results.

**Comment by driesvints** [comment]
Feel free to re-open if the openid provider didn't solve your problem 👍

**Comment by mukes555** [comment]
facing same issue
