### ISSUE TITLE
SocialiteProviders\Apple\Provider::refreshToken(string $refreshToken) compatibility problem

### ISSUE THREAD

**Issue by fabioferreira3** [laravel/socialite#678]
### Socialite Version

5.11.0

### Laravel Version

10.35.0

### PHP Version

8.2.11

### Description

After upgrading package to v5.11.0 this error shows up when using composer dump-autoload:

Whoops\Exception\ErrorException 

 Declaration of SocialiteProviders\Apple\Provider::refreshToken(string $refreshToken): Psr\Http\Message\ResponseInterface must be compatible with Laravel\Socialite\Two\AbstractProvider::refreshToken($refreshToken)

at vendor/socialiteproviders/apple/Provider.php:289

### Steps To Reproduce

- Upgrade to latest v5.11.0 of the package
- Downgrading to v5.10.0 currently is the only way to avoid the issue.

**Comment by driesvints** [comment]
Please see previous issues. This needs to be fixed in the socialite providers repo.
