### ISSUE TITLE
GoogleProvider Not Receiving nickname Key

### ISSUE THREAD

**Issue by falconsmilie** [laravel/socialite#690]
### Socialite Version

5.12.0

### Laravel Version

10.44.0

### PHP Version

8.2

### Description

`\Laravel\Socialite\Two\GoogleProvider::getUserByToken` is not getting `nickname` in the response.

Here's a dump of the `$response->getBody()->getContents()` from within `\Laravel\Socialite\Two\GoogleProvider::getUserByToken`.

```
{
  "sub": "...",
  "name": "...",
  "given_name": "...",
  "picture": "https://lh3.googleusercontent.com/a/...",
  "email": "...@google.com",
  "email_verified": true,
  "locale": "en-GB"
}
```

### Steps To Reproduce

The implementation I've used is quite simple.

A call to: `Socialite::driver('google')->redirect()`.

Redirects to Google. In my case: https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?...

Then assign the result of `Socialite::driver('google')->user()` to a local `$user` var.

`$user->getNickname();` is always `null` (with the 2 different Google accounts I've tried).

**Comment by falconsmilie** [comment]
I'm happy to create a PR, but wanted to know if this is reproducable for anyone else, and if there are any backward compat concerns I need to know about.

**Comment by falconsmilie** [comment]
After reading the Google [docs](https://developers.google.com/identity/openid-connect/openid-connect#obtainuserinfo), and checking the Google accounts i was using to sign in with, i believe this is not really an issue. If the user hasn't set a nickname in their account, then it should return `null` as it is already doing.

**Comment by driesvints** [comment]
Looks like we're not going to take action here for now, sorry.
