### ISSUE TITLE
Issue authenticating

### ISSUE THREAD

**Issue by hermesdj** [laravel/socialite#692]
### Socialite Version

5.12.0

### Laravel Version

10.44.0

### PHP Version

8.1.4

### Database Driver & Version

Mariadb

### Description

Since this PR https://github.com/laravel/socialite/pull/684 adds the authentication clientId and secret in the header and keep it in the form body, some SSO provider throw an error that the value should be in one or the other but not in both. 

### Steps To Reproduce

Trying to authenticate to Eve Online SSO provider https://login.eveonline.com/v2/oauth/token

**Comment by driesvints** [comment]
We unfortunately do not maintain this provider. Please open an issue with this provider's repo.

**Comment by Flightfreak** [comment]
We are also experiencing issues with our providers now. This was a breaking change...

**Comment by driesvints** [comment]
Thanks all. I've in the end reverted the original PR.
