### ISSUE TITLE
Sign In With LinkedIn Not working aymore?

### ISSUE THREAD

**Issue by souhailmerroun** [laravel/socialite#695]
### Socialite Version

latest

### Laravel Version

latest

### PHP Version

latest

### Description

I'm trying to do a login with LinkedIn but it not working. 

I'm doubting it is because of the migration of linkedin from
- https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin
- https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2

It is a scope issue. 

This post explain it better https://github.com/supabase/gotrue/issues/1216#issue-1846849385 

Is this known already? can we expect an update? 

### Steps To Reproduce

Following steps of https://socialiteproviders.com/LinkedIn/

**Comment by crynobone** [comment]
Please submit the issue to https://github.com/SocialiteProviders/LinkedIn
