### ISSUE TITLE
Facebook always returns null for email

### ISSUE THREAD

**Issue by winterhevn** [laravel/socialite#697]
### Socialite Version

5.2

### Laravel Version

8

### PHP Version

7.4

### Description

Facebook always returns null email.
I have checked using dd.
I have checked my Facebook account and it's showing that my email was being used by the app
I have checked the Facebook app and it's showing Advanced Access for email scope.

### Steps To Reproduce

see above

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by winterhevn** [comment]
Hi @driesvints I have actually spent 2 days scouring the internet for solutions already. This is my last stop.

**Comment by driesvints** [comment]
Can you link to the places where you posted the question?

**Comment by winterhevn** [comment]
Lol why. You need proof? What for. Don't answer that.
I didn't. I searched for existing threads that talk about the same issue and found the solutions not applicable to me.
I figured the actual devs would be the best people to find help. Seems not. 
If there's no intention to help, can just close this down.

**Comment by AlexRAtIB** [comment]
https://developers.facebook.com/support/bugs/466007169936699/

We discovered that if your account is internally flagged by Facebook, it may never return an email. The test accounts that Facebook offers in their Developer area worked, while some of our real accounts did not. 

The account continues to return other parameters normally.
