### ISSUE TITLE
Slack does not accept app directory submissions using the legacy `identity.avatar`,`identity.basic`, `identity.email` and `identity.team` scopes

### ISSUE THREAD

**Issue by maartenpaauw** [laravel/socialite#702]
### Socialite Version

5.13.2

### Laravel Version

11.2.0

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

The Slack provider requests the scopes `identity.basic`, `identity.email`, `identity.team` and `identity.avatar`, which are marked as outdated. This means developers cannot register new Slack applications, because the following automated feedback is provided, which blocks the developer for submitting their new application to the Slack app directory.

![Outdated scopes](https://github.com/laravel/socialite/assets/4550875/03d50ad5-85f7-4694-a91f-218b7a90bc71)

Slack suggests to use OpenID instead.

> This scope is part of an outdated approach to Sign in with Slack.
Apps using the Legacy Sign in with Slack protocol can no longer be created, and existing apps using this scope cannot be added to the App directory. We recommend using the [modern Sign in with Slack protocol](https://api.slack.com/authentication/sign-in-with-slack) instead.

See https://api.slack.com/authentication/sign-in-with-slack for more information.

### Steps To Reproduce

Submit an app to the Slack app directory using the scopes `identity.avatar`,`identity.basic`, `identity.email` and `identity.team` and see the error message.

**Comment by maartenpaauw** [comment]
I think a similar solution as the LinkedIn OpenID provider needs to be added? 

https://github.com/laravel/socialite/pull/662

**Comment by maartenpaauw** [comment]
I've managed to create an open id provider implementation. I'll cleanup the code a bit and open up a pull request later this week.

**Comment by driesvints** [comment]
Thanks @maartenpaauw. It indeed seems we need a similar solution like the LinkedIn one if we're gonna do this on the current major release. We'd love to have a PR for this!
