### ISSUE TITLE
Facebook Graph API Version Upgrade

### ISSUE THREAD

**Issue by misagh** [laravel/socialite#705]
Hi.

I noticed that the code is currently using Facebook Graph API v3.3, as seen here: https://github.com/laravel/socialite/blob/beb3adcff1a6e400955c459d5ad329c0576da3ed/src/Two/FacebookProvider.php#L27

According to the latest documentation, the current version of the Facebook Graph API is v20. You can review the changelog here:
https://developers.facebook.com/docs/graph-api/changelog

Do we need to consider upgrading to the latest version to ensure compatibility and access to new features?

Thanks.

**Comment by driesvints** [comment]
Honestly I have no idea. I don't think the current implementation is broken as still many use is. We could consider modernising it in a future major release but we don't have plans to do that ourselves. To be fair as long as the current implementation works I don't see a real reason to change. Socialite allows for basic oauth authentication and most likely doesn't need modern features from newer API versions.

**Comment by omerkoseoglu** [comment]
Hello,

1. Create FacebookProvider.php in app/Providers folder.

```php
<?php
namespace App\Providers;

use Laravel\Socialite\Two\FacebookProvider as SocialiteFacebookProvider;

class FacebookProvider extends SocialiteFacebookProvider
{
    protected $version = 'v20.0';
}
```

2. Add the following code to the boot method in AppServideProvider.

```php
$socialite = $this->app->make('Laravel\Socialite\Contracts\Factory');

$socialite->extend('facebook', function ($app) use ($socialite) {
            $config = $app['config']['services.facebook'];
            return $socialite->buildProvider(FacebookProvider::class, $config);
});
```

That's it.

I tried this solution today and ran it in the production environment. I did not encounter any problems.

**Comment by ChetanTechnource** [comment]
For future references, you may use following `usingGraphVersion` method for same purpose.

```
vendor/laravel/socialite/src/Two/FacebookProvider.php

public function usingGraphVersion(string $version)
{
        $this->version = $version;

        return $this;
}
```

**Comment by Khuthaily** [comment]
I agree with @ChetanTechnource. Socialite already supports this via the `usingGraphVersion(string $version)` method.

Here is how you can implement it in your class (sample code):
```

protected $facebookVersion = 'v22.0';

public function handleProviderCallback(Request $request)
{
    ...
    Socialite::driver('facebook')
                                 ->stateless()
                                 ->usingGraphVersion($this->facebookVersion)
                                 ->user();
    ...
}
```
And
```
public function redirectToProvider(Request $request)
{
    ...
    return Socialite::driver('facebook')
                                       ->usingGraphVersion($this->facebookVersion)
                                       ->redirect();
}
```
