### ISSUE TITLE
Google driver not passing custom params to callback URL

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/socialite#714]
### Socialite Version

5.16.0

### Laravel Version

11.21.0

### PHP Version

8.3.9

### Database Driver & Version

MySQL 8

### Description

Custom `with` params aren't passed back to the callback URL on **google** driver

### Steps To Reproduce

Use Google driver

```php
Socialite::driver('google')->scopes([
    'https://www.googleapis.com/auth/calendar'
])->with(array_merge(['access_type' => 'offline'], [
    'should_activate_integration' => true,
    'integration_id' => 'my-id'
]))->redirect(),
```

Within my `callback` controller I'm using an invoke method accepting in the `Request $request`, and I don't see my `integration_id` or other options here:

```php
$googleUser = Socialite::driver($service)->stateless()->user();

\Log::info('req', [
            'intit' => $request->input('integration_id', 'none'),
            'req' => $request->all()
        ]);
```

**Comment by ev-gor** [comment]
Google OAuth API doesn't support 'integration_id' query string parameter. It supports 'state' parameter and returns 'state' in the response.

**Comment by sts-ryan-holton** [comment]
I ended up passing it in via `state` just for the Google drvier

**Comment by crynobone** [comment]
We are closing this as an alternative solution available. However, anyone is free to submit PR if any improvements need to be made.
