### ISSUE TITLE
Facebook login for business with configuration ID

### ISSUE THREAD

**Issue by ChetanTechnource** [laravel/socialite#716]
### Socialite Version

5.16

### Laravel Version

11.9

### PHP Version

8.3.11

### Database Driver & Version

Mysql 8.0

### Description

My facebook app has been upgraded to use **facebook login for business**. 
When I am trying to login, I am receiving following error : 

```
It looks like this app isn't available
To fix this, please contact *APP NAME*.
```
```
public function redirectToFacebook(): RedirectResponse
{
        return Socialite::driver('facebook')->usingGraphVersion(config('services.facebook.version'))->redirect();
}
```

It would be nice to have method similar to `usingGraphVersion` i.e `usingConfigIdForBusinessLogin(config('services.facebook.configuration_id'))`

### Steps To Reproduce

You should be able to reproduce if you are using facebook login for business.

**Comment by ev-gor** [comment]
According to Facebook's official documentation, you need to add your configuration ID as an optional parameter. So try this and let us know the result
```php
public function redirectToFacebook(): RedirectResponse
{
        return Socialite::driver('facebook')
        ->usingGraphVersion(config('services.facebook.version'))
        ->with(['config_id' => config('services.facebook.configuration_id')])
        ->redirect();
}
```

**Comment by crynobone** [comment]
Thanks @ev-gor

**Comment by Stichoza** [comment]
Thanks @ev-gor! Can you also share how did you create the configuration? What type did you select and what permissions did you add? This is my current config:

- Login variation: General
- Access token: User access token
- Permissions: `email`, `pages_read_engagement`, `pages_show_list`

I'm passing `config_id` in params, but still getting the same "It looks like this app isn't available" error
