### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by unger86** [laravel/socialite#720]
### Socialite Version

1.6.1

### Laravel Version

11

### PHP Version

8.3

### Description

Local - all work!
On prod - hosting error:
`Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response: { "error": "invalid_request", "error_description": "Missing required parameter: code" }`

### Steps To Reproduce

`Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response: { "error": "invalid_request", "error_description": "Missing required parameter: code" }`

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
