### ISSUE TITLE
AZURE AD SOCIALITE

### ISSUE THREAD

**Issue by resujentoezequiel** [laravel/socialite#721]
### Socialite Version

5.16

### Laravel Version

11.0

### PHP Version

8.2

### Description

Good day,

May I know how I can get the "JOB INFORMATION" in the Azure AD? Because right now the job information of the user is not included in the response of socialite.

### Steps To Reproduce

$user = Socialite::driver('azure')->user();

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
