### ISSUE TITLE
[FEATURE_REQUEST] Apple Provider Support

### ISSUE THREAD

**Issue by xcode-it** [laravel/socialite#723]
### Socialite Version

5.16

### Laravel Version

11.34.2

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0

### Description

Why there's no support for apple provider ?

### Steps To Reproduce

```php

    'apple' => [
        'client_id' => env('APPLE_CLIENT_ID'),
        'client_secret' => env('APPLE_CLIENT_SECRET'),
        'redirect' => env("APP_ENV") === "local" ? env('APPLE_DEV_REDIRECT_URI') : env('APPLE_PROD_REDIRECT_URI'),
    ],

```

**Comment by crynobone** [comment]
You should be able to use 3rd party package: https://socialiteproviders.com/Apple/

We have no plan to maintain additional providers: https://github.com/laravel/socialite/issues/369#issuecomment-540592423
