### ISSUE TITLE
VK authorization error

### ISSUE THREAD

**Issue by AlexKomMsk** [laravel/socialite#724]
### Socialite Version

5

### Laravel Version

8

### PHP Version

8.1

### Database Driver & Version

Mysql

### Description

The site uses VK authorization. Yesterday an error appeared in the logs: 
production.ERROR: Invalid JSON response from VK: `{"error":{"error_code":5,"error_msg":"User authorization failed: no access_token passed.","request_params":[{"key":"fields","value":"first_name,last_name,email"},{"key":"lang","value":"en"},{"key":"v","value":"5.131"},{"key":"method","value":"users.get"},{"key":"oauth","value":"1"}]}} {"exception":"[object] (RuntimeException(code: 0): Invalid JSON response from VK: {\"error\":{\"error_code\":5,\"error_msg\":\"User authorization failed: no access_token passed.\",\"request_params\":[{\"key\":\"fields\",\"value\":\"first_name,last_name,email\"},{\"key\":\"lang\",\"value\":\"en\"},{\"key\":\"v\",\"value\":\"5.131\"},{\"key\":\"method\",\"value\":\"users.get\"},{\"key\":\"oauth\",\"value\":\"1\"}]}} at /vendor/socialiteproviders/vkontakte/Provider.php:81)`

### Steps To Reproduce

Try to log in using VK.

**Comment by crynobone** [comment]
We don't maintain `VK`, please submit it to the correct repository.
